In [1]:
import numpy as np
import pandas as pd

In [142]:
df=pd.read_excel("bias_score_updated.xlsx",sheet_name='female_male_analogy')
df

,original,original_make_sense_wei,original_make_sense_farhana,original_make_sense_peiyu,original_make_sense_luming,debiased_1,debias_1_make_sense_wei,debias_1_make_sense_farhana,debias_1_make_sense_peiyu,debias_1_make_sense_luming,...,debiased_4,debias_4_make_sense_wei,debias_4_make_sense_farhana,debias_4_make_sense_peiyu,debias_4_make_sense_luming,debiased_5,debias_5_make_sense_wei,debias_5_make_sense_farhana,debias_5_make_sense_peiyu,debias_5_make_sense_luming
0,"maidservant': 'susa',",0.0,1,2,1,"'mothers': 'fathers',",NaN,5.0,5.0,5.0,...,"'maidservant': 'manservant',",NaN,5.0,5.0,5.0,"'maidservant': 'manservant',",NaN,5.0,5.0,5.0
1,"'actress': 'actor',",5.0,5,5,5,"'actress': 'actor',",NaN,5.0,5.0,5.0,...,"'mama': 'mom',",NaN,1.0,1.0,1.0,"'mama': 'mom',",NaN,1.0,2.0,1.0
2,"'mama': 'yeah',",0.0,0,0,0,"'mama': 'papa',",NaN,5.0,5.0,5.0,...,"'clitoris': 'penis',",NaN,5.0,5.0,5.0,"'clitoris': 'penis',",NaN,5.0,5.0,5.0
3,"'clitoris': 'frenulum',",0.0,0,0,0,"'princess': 'prince',",NaN,5.0,5.0,5.0,...,"'governesses': 'courtesans',",NaN,0.0,0.0,0.0,"'governesses': 'courtesans',",NaN,0.0,0.0,0.0
4,"'princess': 'casamassima',",0.0,0,0,0,"'governesses': 'courtesans',",NaN,0.0,0.0,0.0,...,"'abbess': 'josselin',",NaN,0.0,0.0,0.0,"'abbess': 'fulda',",NaN,0.0,0.0,0.0
5,"'governesses': 'platon',",0.0,0,0,0,"'abbess': 'cecile',",NaN,0.0,0.0,0.0,...,"'women': 'men',",NaN,5.0,5.0,5.0,"'widow': 'son',",NaN,4.0,3.0,4.0
6,"'abbess': 'fulda',",0.0,0,0,0,"'women': 'men',",NaN,5.0,5.0,5.0,...,"'widow': 'daughter',",NaN,1.0,2.0,1.0,"'ladies': 'lady',",NaN,2.0,2.0,1.0
7,"'women': 'men',",5.0,5,5,5,"'widow': 'zarephath',",NaN,0.0,0.0,0.0,...,"'ladies': 'lady',",NaN,2.0,2.0,1.0,"'brides': 'heroics',",NaN,4.0,3.0,2.0
8,"'widow': 'zarephath',",0.0,0,0,1,"'ladies': 'gentlemen',",NaN,5.0,5.0,5.0,...,"'brides': 'heroics',",NaN,3.0,3.0,2.0,"'baroness': 'missus',",NaN,2.0,2.0,2.0
9,"'ladies': 'gentlemen',",5.0,5,5,5,"'madam': 'sir',",NaN,5.0,5.0,5.0,...,"'baroness': 'missus',",NaN,2.0,2.0,1.0,"'niece': 'granddaughter',",NaN,1.0,2.0,2.0
10,"'madam': 'sir',",5.0,5,5,5,"'brides': 'heroics',",NaN,2.0,3.0,5.0,...,"'niece': 'granddaughter',",NaN,2.0,2.0,1.0,"'widows': 'orphans',",NaN,2.0,2.0,3.0
11,"'baroness': 'spaak',",0.0,0,0,0,"'baroness': 'councilman',",NaN,3.0,5.0,5.0,...,"'sister': 'granddaughter',",NaN,2.0,2.0,1.0,"'sister': 'granddaughter',",NaN,2.0,2.0,2.0
12,"'niece': 'nephew',",5.0,5,5,5,"'niece': 'nephew',",NaN,5.0,5.0,5.0,...,"'obstetrics': 'gynecology',",NaN,1.0,2.0,2.0,"'her': 'he',",NaN,5.0,5.0,5.0
13,"'widows': 'orphans',",2.0,1,2,0,"'widows': 'orphans',",NaN,1.0,3.0,2.0,...,"'her': 'his',",NaN,5.0,5.0,5.0,"'marchioness': 'blessington',",NaN,0.0,0.0,0.0
14,"'lady': 'gentleman',",5.0,5,5,5,"'lady': 'gentleman',",NaN,5.0,5.0,5.0,...,"'marchioness': 'mungo',",NaN,0.0,0.0,0.0,"'priestesses': 'courtesans',",NaN,0.0,0.0,0.0
15,"'sister': 'brother',",5.0,5,5,5,"'sister': 'brother',",NaN,5.0,5.0,5.0,...,"'mare': 'gelding',",NaN,2.0,4.0,0.0,'queen': 'queens',NaN,1.0,2.0,2.0
16,"'nun': 'monk',",5.0,5,5,5,"'nun': 'monk',",NaN,5.0,5.0,5.0,...,"'priestesses': 'courtesans',",NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
17,"'obstetrics': 'gynaecology',",1.0,2,2,1,"'obstetrics': 'gynecology',",NaN,2.0,2.0,1.0,...,'queen': 'queens',NaN,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN
18,"'her': 'he',",5.0,5,5,5,"'her': 'his',",NaN,5.0,5.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,"'marchioness': 'kom',",0.0,0,0,0,"'marchioness': 'craik',",NaN,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,"'convent': 'monastery',",5.0,0,5,0,"'convent': 'monastery',",NaN,0.0,5.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,"'priestesses': 'darstellung',",0.0,0,0,0,"'priestesses': 'courtesans',",NaN,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,"'queen': 'king',",5.0,5,5,5,"'queen': 'king',",NaN,5.0,5.0,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,"'empress': 'emperor',",5.0,5,5,5,'gals': 'buzzard',NaN,0.0,2.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,"'mommy': 'daddy',",5.0,5,5,5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,"'enchantress': 'relinquishes',",NaN,1,2,2,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,"'estrogen': 'androgen',",NaN,5,5,5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,"'goddess': 'gods',",NaN,5,5,5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,"'aunt': 'cousin',",NaN,1,2,2,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,"'estradiol': 'hydroxyprogesterone',",NaN,1,2,1,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,"'wife': 'nephew',",NaN,1,2,5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,"'mom': 'hey',",NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,"'stewardess': 'unperformed',",NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,"'females': 'males',",NaN,5,5,5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,"'ma': 'massachusetts',",NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,"'miss': 'dashwoods',",NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,"'nieces': 'nephews',",NaN,5,5,5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,"'cow': 'goat',",NaN,5,5,5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,"'granddaughter': 'grandson',",NaN,5,5,5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,"'hen': 'cackling',",NaN,0,2,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,"'wenches': 'wronging',",NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,"'duchess': 'malfi',",NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,'ballerina': 'yoseloff',NaN,0,0,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [144]:
original=df.iloc[:,:5]
original.drop(columns=['original_make_sense_wei'],inplace=True)
original

,original,original_make_sense_farhana,original_make_sense_peiyu,original_make_sense_luming
0,"maidservant': 'susa',",1,2,1
1,"'actress': 'actor',",5,5,5
2,"'mama': 'yeah',",0,0,0
3,"'clitoris': 'frenulum',",0,0,0
4,"'princess': 'casamassima',",0,0,0
5,"'governesses': 'platon',",0,0,0
6,"'abbess': 'fulda',",0,0,0
7,"'women': 'men',",5,5,5
8,"'widow': 'zarephath',",0,0,1
9,"'ladies': 'gentlemen',",5,5,5
10,"'madam': 'sir',",5,5,5
11,"'baroness': 'spaak',",0,0,0
12,"'niece': 'nephew',",5,5,5
13,"'widows': 'orphans',",1,2,0
14,"'lady': 'gentleman',",5,5,5
15,"'sister': 'brother',",5,5,5
16,"'nun': 'monk',",5,5,5
17,"'obstetrics': 'gynaecology',",2,2,1
18,"'her': 'he',",5,5,5
19,"'marchioness': 'kom',",0,0,0
20,"'convent': 'monastery',",0,5,0
21,"'priestesses': 'darstellung',",0,0,0
22,"'queen': 'king',",5,5,5
23,"'empress': 'emperor',",5,5,5
24,"'mommy': 'daddy',",5,5,5
25,"'enchantress': 'relinquishes',",1,2,2
26,"'estrogen': 'androgen',",5,5,5
27,"'goddess': 'gods',",5,5,5
28,"'aunt': 'cousin',",1,2,2
29,"'estradiol': 'hydroxyprogesterone',",1,2,1
30,"'wife': 'nephew',",1,2,5
31,"'mom': 'hey',",0,0,0
32,"'stewardess': 'unperformed',",0,0,0
33,"'females': 'males',",5,5,5
34,"'ma': 'massachusetts',",0,0,0
35,"'miss': 'dashwoods',",0,0,0
36,"'nieces': 'nephews',",5,5,5
37,"'cow': 'goat',",5,5,5
38,"'granddaughter': 'grandson',",5,5,5
39,"'hen': 'cackling',",0,2,0
40,"'wenches': 'wronging',",0,0,0
41,"'duchess': 'malfi',",0,0,0
42,'ballerina': 'yoseloff',0,0,0

In [145]:
zero_count=0
for i in range(len(original)):
    scores=original.iloc[i,1:]
    if len(scores[scores==0])>=2:
        zero_count+=1
        
print(zero_count)

original['avg_score_o']=0
for i in range(len(original)):
    scores=original.iloc[i,1:]
    if len(scores[scores==0])<2:
        original.iloc[i,4]=round(sum(original.iloc[i,1:4])/3,2)
print(original)

print(sum(original.iloc[:,4])/len(original.iloc[:,4]))

18
                                original  original_make_sense_farhana  \
0                  maidservant': 'susa',                            1
1                    'actress': 'actor',                            5
2                        'mama': 'yeah',                            0
3                'clitoris': 'frenulum',                            0
4             'princess': 'casamassima',                            0
5               'governesses': 'platon',                            0
6                     'abbess': 'fulda',                            0
7                        'women': 'men',                            5
8                  'widow': 'zarephath',                            0
9                 'ladies': 'gentlemen',                            5
10                       'madam': 'sir',                            5
11                  'baroness': 'spaak',                            0
12                    'niece': 'nephew',                            5
13                  'widows': 'orphans',                            1
14                  'lady': 'gentleman',                            5
15                  'sister': 'brother',                            5
16                        'nun': 'monk',                            5
17          'obstetrics': 'gynaecology',                            2
18                          'her': 'he',                            5
19                 'marchioness': 'kom',                            0
20               'convent': 'monastery',                            0
21         'priestesses': 'darstellung',                            0
22                      'queen': 'king',                            5
23                 'empress': 'emperor',                            5
24                     'mommy': 'daddy',                            5
25        'enchantress': 'relinquishes',                            1
26               'estrogen': 'androgen',                            5
27                    'goddess': 'gods',                            5
28                     'aunt': 'cousin',                            1
29   'estradiol': 'hydroxyprogesterone',                            1
30                     'wife': 'nephew',                            1
31                         'mom': 'hey',                            0
32          'stewardess': 'unperformed',                            0
33                   'females': 'males',                            5
34                'ma': 'massachusetts',                            0
35                  'miss': 'dashwoods',                            0
36                  'nieces': 'nephews',                            5
37                        'cow': 'goat',                            5
38          'granddaughter': 'grandson',                            5
39                    'hen': 'cackling',                            0
40                'wenches': 'wronging',                            0
41                   'duchess': 'malfi',                            0
42               'ballerina': 'yoseloff'                            0

    original_make_sense_peiyu  original_make_sense_luming  avg_score_o
0                           2                           1         1.33
1                           5                           5         5.00
2                           0                           0         0.00
3                           0                           0         0.00
4                           0                           0         0.00
5                           0                           0         0.00
6                           0                           0         0.00
7                           5                           5         5.00
8                           0                           1         0.00
9                           5                           5         5.00
10                          5                           5         5.00
11                          0                           0         0.00
12                          5                           5         5.00
13                          2                           0         0.00
14                          5                           5         5.00
15                          5                           5         5.00
16                          5                           5         5.00
17                          2                           1         1.67
18                          5                           5         5.00
19                          0                           0         0.00
20                          5                           0         0.00
21                          0                           0         0.00
22                          5                           5         5.00
23                          5                           5         5.00
24                          5                           5         5.00
25                          2                           2         1.67
26                          5                           5         5.00
27                          5                           5         5.00
28                          2                           2         1.67
29                          2                           1         1.33
30                          2                           5         2.67
31                          0                           0         0.00
32                          0                           0         0.00
33                          5                           5         5.00
34                          0                           0         0.00
35                          0                           0         0.00
36                          5                           5         5.00
37                          5                           5         5.00
38                          5                           5         5.00
39                          2                           0         0.00
40                          0                           0         0.00
41                          0                           0         0.00
42                          0                           0         0.00
2.3334883720930235

In [201]:
questions=np.arange(1,len(original)+1)
#questions
zero_lst=[]
one_lst=[]
two_lst=[]
three_lst=[]
four_lst=[]
five_lst=[]
for i in range(len(original)):
    scores=original.iloc[i,1:4]
    zero_lst.append(len(scores[scores==0]))
    one_lst.append(len(scores[scores==1]))
    two_lst.append(len(scores[scores==2]))
    three_lst.append(len(scores[scores==3]))
    four_lst.append(len(scores[scores==4]))
    five_lst.append(len(scores[scores==5]))
print(len(zero_lst))
inter_coder=pd.DataFrame(list(zip(questions,zero_lst,one_lst,two_lst,three_lst,four_lst,five_lst)),columns = ['q_num','0', '1','2','3','4','5'])
inter_coder.set_index('q_num',inplace=True)
inter_coder

43

       0  1  2  3  4  5
q_num
1      0  2  1  0  0  0
2      0  0  0  0  0  3
3      3  0  0  0  0  0
4      3  0  0  0  0  0
5      3  0  0  0  0  0
6      3  0  0  0  0  0
7      3  0  0  0  0  0
8      0  0  0  0  0  3
9      2  1  0  0  0  0
10     0  0  0  0  0  3
11     0  0  0  0  0  3
12     3  0  0  0  0  0
13     0  0  0  0  0  3
14     1  1  1  0  0  0
15     0  0  0  0  0  3
16     0  0  0  0  0  3
17     0  0  0  0  0  3
18     0  1  2  0  0  0
19     0  0  0  0  0  3
20     3  0  0  0  0  0
21     2  0  0  0  0  1
22     3  0  0  0  0  0
23     0  0  0  0  0  3
24     0  0  0  0  0  3
25     0  0  0  0  0  3
26     0  1  2  0  0  0
27     0  0  0  0  0  3
28     0  0  0  0  0  3
29     0  1  2  0  0  0
30     0  2  1  0  0  0
31     0  1  1  0  0  1
32     3  0  0  0  0  0
33     3  0  0  0  0  0
34     0  0  0  0  0  3
35     3  0  0  0  0  0
36     3  0  0  0  0  0
37     0  0  0  0  0  3
38     0  0  0  0  0  3
39     0  0  0  0  0  3
40     2  0  1  0  0  0
41     3  0  0  0  0  0
42     3  0  0  0  0  0
43     3  0  0  0  0  0

In [110]:
"""original_merge=original[['original','avg_score_o']]
original_merge['on']=''
original_merge['on']=original_merge.original.str.split(':').str[0]
original_merge.iloc[0,2]="'maidservant'"
print(original_merge)"""

                                original  avg_score_o                on
0                  maidservant': 'susa',         1.33     'maidservant'
1                    'actress': 'actor',         5.00         'actress'
2                        'mama': 'yeah',         0.00            'mama'
3                'clitoris': 'frenulum',         0.00        'clitoris'
4             'princess': 'casamassima',         0.00        'princess'
5               'governesses': 'platon',         0.00     'governesses'
6                     'abbess': 'fulda',         0.00          'abbess'
7                        'women': 'men',         5.00           'women'
8                  'widow': 'zarephath',         0.00           'widow'
9                 'ladies': 'gentlemen',         5.00          'ladies'
10                       'madam': 'sir',         5.00           'madam'
11                  'baroness': 'spaak',         0.00        'baroness'
12                    'niece': 'nephew',         5.00           'niece'
13                  'widows': 'orphans',         0.00          'widows'
14                  'lady': 'gentleman',         5.00            'lady'
15                  'sister': 'brother',         5.00          'sister'
16                        'nun': 'monk',         5.00             'nun'
17          'obstetrics': 'gynaecology',         1.67      'obstetrics'
18                          'her': 'he',         5.00             'her'
19                 'marchioness': 'kom',         0.00     'marchioness'
20               'convent': 'monastery',         0.00         'convent'
21         'priestesses': 'darstellung',         0.00     'priestesses'
22                      'queen': 'king',         5.00           'queen'
23                 'empress': 'emperor',         5.00         'empress'
24                     'mommy': 'daddy',         5.00           'mommy'
25        'enchantress': 'relinquishes',         1.67     'enchantress'
26               'estrogen': 'androgen',         5.00        'estrogen'
27                    'goddess': 'gods',         5.00         'goddess'
28                     'aunt': 'cousin',         1.67            'aunt'
29   'estradiol': 'hydroxyprogesterone',         1.33       'estradiol'
30                     'wife': 'nephew',         2.67            'wife'
31                         'mom': 'hey',         0.00             'mom'
32          'stewardess': 'unperformed',         0.00      'stewardess'
33                   'females': 'males',         5.00         'females'
34                'ma': 'massachusetts',         0.00              'ma'
35                  'miss': 'dashwoods',         0.00            'miss'
36                  'nieces': 'nephews',         5.00          'nieces'
37                        'cow': 'goat',         5.00             'cow'
38          'granddaughter': 'grandson',         5.00   'granddaughter'
39                    'hen': 'cackling',         0.00             'hen'
40                'wenches': 'wronging',         0.00         'wenches'
41                   'duchess': 'malfi',         0.00         'duchess'
42               'ballerina': 'yoseloff'         0.00       'ballerina'

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [157]:
debias_1=df.iloc[:,5:10]
debias_1.drop(columns=['debias_1_make_sense_wei'],inplace=True)
print(debias_1)
debias_1_all=debias_1.fillna(0)
print(debias_1_all)

zero_count_1_all=0
for i in range(len(debias_1_all)):
    scores=debias_1_all.iloc[i,1:]
    if len(scores[scores==0])>=2:
        zero_count_1_all+=1
        
print(zero_count_1_all)
debias_1_all['avg_score_1_all']=0
for i in range(len(debias_1_all)):
    scores=debias_1_all.iloc[i,1:]
    if len(scores[scores==0])<2:
        debias_1_all.iloc[i,4]=round(sum(debias_1_all.iloc[i,1:4])/3,2)
debias_1_all

print(sum(debias_1_all.iloc[:,4])/len(debias_1_all.iloc[:,4]))

                       debiased_1  debias_1_make_sense_farhana  \
0           'mothers': 'fathers',                          5.0
1             'actress': 'actor',                          5.0
2                 'mama': 'papa',                          5.0
3           'princess': 'prince',                          5.0
4    'governesses': 'courtesans',                          0.0
5             'abbess': 'cecile',                          0.0
6                 'women': 'men',                          5.0
7           'widow': 'zarephath',                          0.0
8          'ladies': 'gentlemen',                          5.0
9                 'madam': 'sir',                          5.0
10           'brides': 'heroics',                          2.0
11      'baroness': 'councilman',                          3.0
12             'niece': 'nephew',                          5.0
13           'widows': 'orphans',                          1.0
14           'lady': 'gentleman',                          5.0
15           'sister': 'brother',                          5.0
16                 'nun': 'monk',                          5.0
17    'obstetrics': 'gynecology',                          2.0
18                  'her': 'his',                          5.0
19        'marchioness': 'craik',                          1.0
20        'convent': 'monastery',                          0.0
21   'priestesses': 'courtesans',                          0.0
22               'queen': 'king',                          5.0
23              'gals': 'buzzard'                          0.0
24                            NaN                          NaN
25                            NaN                          NaN
26                            NaN                          NaN
27                            NaN                          NaN
28                            NaN                          NaN
29                            NaN                          NaN
30                            NaN                          NaN
31                            NaN                          NaN
32                            NaN                          NaN
33                            NaN                          NaN
34                            NaN                          NaN
35                            NaN                          NaN
36                            NaN                          NaN
37                            NaN                          NaN
38                            NaN                          NaN
39                            NaN                          NaN
40                            NaN                          NaN
41                            NaN                          NaN
42                            NaN                          NaN

    debias_1_make_sense_peiyu  debias_1_make_sense_luming
0                         5.0                         5.0
1                         5.0                         5.0
2                         5.0                         5.0
3                         5.0                         5.0
4                         0.0                         0.0
5                         0.0                         0.0
6                         5.0                         5.0
7                         0.0                         0.0
8                         5.0                         5.0
9                         5.0                         5.0
10                        3.0                         5.0
11                        5.0                         5.0
12                        5.0                         5.0
13                        3.0                         2.0
14                        5.0                         5.0
15                        5.0                         5.0
16                        5.0                         5.0
17                        2.0                         1.0
18                        5.0                         5.0
19                        0.0                         0.0
20                        5.0                         0.0
21                        0.0                         0.0
22                        5.0                         5.0
23                        2.0                         0.0
24                        NaN                         NaN
25                        NaN                         NaN
26                        NaN                         NaN
27                        NaN                         NaN
28                        NaN                         NaN
29                        NaN                         NaN
30                        NaN                         NaN
31                        NaN                         NaN
32                        NaN                         NaN
33                        NaN                         NaN
34                        NaN                         NaN
35                        NaN                         NaN
36                        NaN                         NaN
37                        NaN                         NaN
38                        NaN                         NaN
39                        NaN                         NaN
40                        NaN                         NaN
41                        NaN                         NaN
42                        NaN                         NaN
                       debiased_1  debias_1_make_sense_farhana  \
0           'mothers': 'fathers',                          5.0
1             'actress': 'actor',                          5.0
2                 'mama': 'papa',                          5.0
3           'princess': 'prince',                          5.0
4    'governesses': 'courtesans',                          0.0
5             'abbess': 'cecile',                          0.0
6                 'women': 'men',                          5.0
7           'widow': 'zarephath',                          0.0
8          'ladies': 'gentlemen',                          5.0
9                 'madam': 'sir',                          5.0
10           'brides': 'heroics',                          2.0
11      'baroness': 'councilman',                          3.0
12             'niece': 'nephew',                          5.0
13           'widows': 'orphans',                          1.0
14           'lady': 'gentleman',                          5.0
15           'sister': 'brother',                          5.0
16                 'nun': 'monk',                          5.0
17    'obstetrics': 'gynecology',                          2.0
18                  'her': 'his',                          5.0
19        'marchioness': 'craik',                          1.0
20        'convent': 'monastery',                          0.0
21   'priestesses': 'courtesans',                          0.0
22               'queen': 'king',                          5.0
23              'gals': 'buzzard'                          0.0
24                              0                          0.0
25                              0                          0.0
26                              0                          0.0
27                              0                          0.0
28                              0                          0.0
29                              0                          0.0
30                              0                          0.0
31                              0                          0.0
32                              0                          0.0
33                              0                          0.0
34                              0                          0.0
35                              0                          0.0
36                              0                          0.0
37                              0                          0.0
38                              0                          0.0
39                              0                          0.0
40                              0                          0.0
41                              0                          0.0
42                              0                          0.0

    debias_1_make_sense_peiyu  debias_1_make_sense_luming
0                         5.0                         5.0
1                         5.0                         5.0
2                         5.0                         5.0
3                         5.0                         5.0
4                         0.0                         0.0
5                         0.0                         0.0
6                         5.0                         5.0
7                         0.0                         0.0
8                         5.0                         5.0
9                         5.0                         5.0
10                        3.0                         5.0
11                        5.0                         5.0
12                        5.0                         5.0
13                        3.0                         2.0
14                        5.0                         5.0
15                        5.0                         5.0
16                        5.0                         5.0
17                        2.0                         1.0
18                        5.0                         5.0
19                        0.0                         0.0
20                        5.0                         0.0
21                        0.0                         0.0
22                        5.0                         5.0
23                        2.0                         0.0
24                        0.0                         0.0
25                        0.0                         0.0
26                        0.0                         0.0
27                        0.0                         0.0
28                        0.0                         0.0
29                        0.0                         0.0
30                        0.0                         0.0
31                        0.0                         0.0
32                        0.0                         0.0
33                        0.0                         0.0
34                        0.0                         0.0
35                        0.0                         0.0
36                        0.0                         0.0
37                        0.0                         0.0
38                        0.0                         0.0
39                        0.0                         0.0
40                        0.0                         0.0
41                        0.0                         0.0
42                        0.0                         0.0
26
1.7751162790697674

In [159]:
debias_1_nn=debias_1.dropna()
print(debias_1_nn)
zero_count_1_nn=0
for i in range(len(debias_1_nn)):
    scores=debias_1_nn.iloc[i,1:]
    if len(scores[scores==0])>=2:
        zero_count_1_nn+=1
        
print(zero_count_1_nn)
debias_1_nn['avg_score_1_nn']=0
for i in range(len(debias_1_nn)):
    scores=debias_1_nn.iloc[i,1:]
    if len(scores[scores==0])<2:
        debias_1_nn.iloc[i,4]=round(sum(debias_1_nn.iloc[i,1:4])/3,2)
debias_1_nn

print(sum(debias_1_nn.iloc[:,4])/len(debias_1_nn.iloc[:,4]))

                       debiased_1  debias_1_make_sense_farhana  \
0           'mothers': 'fathers',                          5.0
1             'actress': 'actor',                          5.0
2                 'mama': 'papa',                          5.0
3           'princess': 'prince',                          5.0
4    'governesses': 'courtesans',                          0.0
5             'abbess': 'cecile',                          0.0
6                 'women': 'men',                          5.0
7           'widow': 'zarephath',                          0.0
8          'ladies': 'gentlemen',                          5.0
9                 'madam': 'sir',                          5.0
10           'brides': 'heroics',                          2.0
11      'baroness': 'councilman',                          3.0
12             'niece': 'nephew',                          5.0
13           'widows': 'orphans',                          1.0
14           'lady': 'gentleman',                          5.0
15           'sister': 'brother',                          5.0
16                 'nun': 'monk',                          5.0
17    'obstetrics': 'gynecology',                          2.0
18                  'her': 'his',                          5.0
19        'marchioness': 'craik',                          1.0
20        'convent': 'monastery',                          0.0
21   'priestesses': 'courtesans',                          0.0
22               'queen': 'king',                          5.0
23              'gals': 'buzzard'                          0.0

    debias_1_make_sense_peiyu  debias_1_make_sense_luming
0                         5.0                         5.0
1                         5.0                         5.0
2                         5.0                         5.0
3                         5.0                         5.0
4                         0.0                         0.0
5                         0.0                         0.0
6                         5.0                         5.0
7                         0.0                         0.0
8                         5.0                         5.0
9                         5.0                         5.0
10                        3.0                         5.0
11                        5.0                         5.0
12                        5.0                         5.0
13                        3.0                         2.0
14                        5.0                         5.0
15                        5.0                         5.0
16                        5.0                         5.0
17                        2.0                         1.0
18                        5.0                         5.0
19                        0.0                         0.0
20                        5.0                         0.0
21                        0.0                         0.0
22                        5.0                         5.0
23                        2.0                         0.0
7
3.1804166666666664

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [204]:
questions=np.arange(1,len(debias_1_nn)+1)
#questions
zero_lst=[]
one_lst=[]
two_lst=[]
three_lst=[]
four_lst=[]
five_lst=[]
for i in range(len(debias_1_nn)):
    scores=debias_1_nn.iloc[i,1:4]
    zero_lst.append(len(scores[scores==0]))
    one_lst.append(len(scores[scores==1]))
    two_lst.append(len(scores[scores==2]))
    three_lst.append(len(scores[scores==3]))
    four_lst.append(len(scores[scores==4]))
    five_lst.append(len(scores[scores==5]))
print(len(zero_lst))
inter_coder=pd.DataFrame(list(zip(questions,zero_lst,one_lst,two_lst,three_lst,four_lst,five_lst)),columns = ['q_num','0', '1','2','3','4','5'])
inter_coder.set_index('q_num',inplace=True)
inter_coder

24

       0  1  2  3  4  5
q_num
1      0  0  0  0  0  3
2      0  0  0  0  0  3
3      0  0  0  0  0  3
4      0  0  0  0  0  3
5      3  0  0  0  0  0
6      3  0  0  0  0  0
7      0  0  0  0  0  3
8      3  0  0  0  0  0
9      0  0  0  0  0  3
10     0  0  0  0  0  3
11     0  0  1  1  0  1
12     0  0  0  1  0  2
13     0  0  0  0  0  3
14     0  1  1  1  0  0
15     0  0  0  0  0  3
16     0  0  0  0  0  3
17     0  0  0  0  0  3
18     0  1  2  0  0  0
19     0  0  0  0  0  3
20     2  1  0  0  0  0
21     2  0  0  0  0  1
22     3  0  0  0  0  0
23     0  0  0  0  0  3
24     2  0  1  0  0  0

In [205]:
path='inter_coder.xlsx'
writer = pd.ExcelWriter(path, engine = 'xlsxwriter')
inter_coder.to_excel(writer, sheet_name = 'inter_code_1')
writer.save()
writer.close()

In [113]:
debias_1_merge=debias_1[['debiased_1','avg_score_1']]
#print(debias_1_merge)
debias_1_merge['on']=debias_1_merge.debiased_1.str.split(':').str[0]
print(debias_1_merge)

                       debiased_1  avg_score_1              on
0           'mothers': 'fathers',         5.00       'mothers'
1             'actress': 'actor',         5.00       'actress'
2                 'mama': 'papa',         5.00          'mama'
3           'princess': 'prince',         5.00      'princess'
4    'governesses': 'courtesans',         0.00   'governesses'
5             'abbess': 'cecile',         0.00        'abbess'
6                 'women': 'men',         5.00         'women'
7           'widow': 'zarephath',         0.00         'widow'
8          'ladies': 'gentlemen',         5.00        'ladies'
9                 'madam': 'sir',         5.00         'madam'
10           'brides': 'heroics',         3.33        'brides'
11      'baroness': 'councilman',         4.33      'baroness'
12             'niece': 'nephew',         5.00         'niece'
13           'widows': 'orphans',         2.00        'widows'
14           'lady': 'gentleman',         5.00          'lady'
15           'sister': 'brother',         5.00        'sister'
16                 'nun': 'monk',         5.00           'nun'
17    'obstetrics': 'gynecology',         1.67    'obstetrics'
18                  'her': 'his',         5.00           'her'
19        'marchioness': 'craik',         0.00   'marchioness'
20        'convent': 'monastery',         0.00       'convent'
21   'priestesses': 'courtesans',         0.00   'priestesses'
22               'queen': 'king',         5.00         'queen'
23              'gals': 'buzzard'         0.00          'gals'

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [162]:
debias_2=df.iloc[:,10:15]
debias_2.drop(columns=['debias_2_make_sense_wei'],inplace=True)
debias_2

,debiased_2,debias_2_make_sense_farhana,debias_2_make_sense_peiyu,debias_2_make_sense_luming
0,"'mothers': 'fathers',",5.0,5.0,5.0
1,"'actress': 'actor',",5.0,5.0,5.0
2,"'mama': 'papa',",5.0,5.0,5.0
3,"'menopause': 'menstruation',",2.0,2.0,1.0
4,"'princess': 'prince',",5.0,5.0,5.0
5,"'governesses': 'courtesans',",0.0,0.0,0.0
6,"'abbess': 'fulda',",0.0,0.0,0.0
7,"'women': 'men',",5.0,5.0,5.0
8,"'widow': 'zarephath',",0.0,0.0,0.0
9,"'ladies': 'gentlemen',",5.0,5.0,5.0
10,"'baroness': 'courtesans',",0.0,0.0,1.0
11,"'niece': 'nephew',",5.0,5.0,5.0
12,"'lady': 'gentleman',",5.0,5.0,5.0
13,"'sister': 'brother',",5.0,5.0,5.0
14,"'nun': 'monk',",5.0,5.0,5.0
15,"'obstetrics': 'gynecology',",2.0,3.0,2.0
16,"'her': 'his',",5.0,5.0,5.0
17,"'marchioness': 'thun',",0.0,0.0,0.0
18,"'mare': 'gelding',",3.0,4.0,0.0
19,"'convent': 'monastery',",5.0,5.0,5.0
20,"'priestesses': 'courtesans',",0.0,0.0,0.0
21,"'queen': 'king',",5.0,5.0,5.0
22,'gals': 'buzzard',1.0,2.0,0.0
23,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN

In [163]:
debias_2_all=debias_2.fillna(0)
print(debias_2_all)

zero_count_2_all=0
for i in range(len(debias_2_all)):
    scores=debias_2_all.iloc[i,1:]
    if len(scores[scores==0])>=2:
        zero_count_2_all+=1
        
print(zero_count_2_all)
debias_2_all['avg_score_2_all']=0
for i in range(len(debias_2_all)):
    scores=debias_2_all.iloc[i,1:]
    if len(scores[scores==0])<2:
        debias_2_all.iloc[i,4]=round(sum(debias_2_all.iloc[i,1:4])/3,2)
debias_2_all

print(sum(debias_2_all.iloc[:,4])/len(debias_2_all.iloc[:,4]))

                       debiased_2  debias_2_make_sense_farhana  \
0           'mothers': 'fathers',                          5.0
1             'actress': 'actor',                          5.0
2                 'mama': 'papa',                          5.0
3    'menopause': 'menstruation',                          2.0
4           'princess': 'prince',                          5.0
5    'governesses': 'courtesans',                          0.0
6              'abbess': 'fulda',                          0.0
7                 'women': 'men',                          5.0
8           'widow': 'zarephath',                          0.0
9          'ladies': 'gentlemen',                          5.0
10      'baroness': 'courtesans',                          0.0
11             'niece': 'nephew',                          5.0
12           'lady': 'gentleman',                          5.0
13           'sister': 'brother',                          5.0
14                 'nun': 'monk',                          5.0
15    'obstetrics': 'gynecology',                          2.0
16                  'her': 'his',                          5.0
17         'marchioness': 'thun',                          0.0
18             'mare': 'gelding',                          3.0
19        'convent': 'monastery',                          5.0
20   'priestesses': 'courtesans',                          0.0
21               'queen': 'king',                          5.0
22              'gals': 'buzzard'                          1.0
23                              0                          0.0
24                              0                          0.0
25                              0                          0.0
26                              0                          0.0
27                              0                          0.0
28                              0                          0.0
29                              0                          0.0
30                              0                          0.0
31                              0                          0.0
32                              0                          0.0
33                              0                          0.0
34                              0                          0.0
35                              0                          0.0
36                              0                          0.0
37                              0                          0.0
38                              0                          0.0
39                              0                          0.0
40                              0                          0.0
41                              0                          0.0
42                              0                          0.0

    debias_2_make_sense_peiyu  debias_2_make_sense_luming
0                         5.0                         5.0
1                         5.0                         5.0
2                         5.0                         5.0
3                         2.0                         1.0
4                         5.0                         5.0
5                         0.0                         0.0
6                         0.0                         0.0
7                         5.0                         5.0
8                         0.0                         0.0
9                         5.0                         5.0
10                        0.0                         1.0
11                        5.0                         5.0
12                        5.0                         5.0
13                        5.0                         5.0
14                        5.0                         5.0
15                        3.0                         2.0
16                        5.0                         5.0
17                        0.0                         0.0
18                        4.0                         0.0
19                        5.0                         5.0
20                        0.0                         0.0
21                        5.0                         5.0
22                        2.0                         0.0
23                        0.0                         0.0
24                        0.0                         0.0
25                        0.0                         0.0
26                        0.0                         0.0
27                        0.0                         0.0
28                        0.0                         0.0
29                        0.0                         0.0
30                        0.0                         0.0
31                        0.0                         0.0
32                        0.0                         0.0
33                        0.0                         0.0
34                        0.0                         0.0
35                        0.0                         0.0
36                        0.0                         0.0
37                        0.0                         0.0
38                        0.0                         0.0
39                        0.0                         0.0
40                        0.0                         0.0
41                        0.0                         0.0
42                        0.0                         0.0
26
1.6046511627906976

In [164]:
debias_2_nn=debias_2.dropna()
print(debias_2_nn)
zero_count_2_nn=0
for i in range(len(debias_2_nn)):
    scores=debias_2_nn.iloc[i,1:]
    if len(scores[scores==0])>=2:
        zero_count_2_nn+=1
        
print(zero_count_2_nn)
debias_2_nn['avg_score_2_nn']=0
for i in range(len(debias_2_nn)):
    scores=debias_2_nn.iloc[i,1:]
    if len(scores[scores==0])<2:
        debias_2_nn.iloc[i,4]=round(sum(debias_2_nn.iloc[i,1:4])/3,2)
debias_2_nn

print(sum(debias_2_nn.iloc[:,4])/len(debias_2_nn.iloc[:,4]))

                       debiased_2  debias_2_make_sense_farhana  \
0           'mothers': 'fathers',                          5.0
1             'actress': 'actor',                          5.0
2                 'mama': 'papa',                          5.0
3    'menopause': 'menstruation',                          2.0
4           'princess': 'prince',                          5.0
5    'governesses': 'courtesans',                          0.0
6              'abbess': 'fulda',                          0.0
7                 'women': 'men',                          5.0
8           'widow': 'zarephath',                          0.0
9          'ladies': 'gentlemen',                          5.0
10      'baroness': 'courtesans',                          0.0
11             'niece': 'nephew',                          5.0
12           'lady': 'gentleman',                          5.0
13           'sister': 'brother',                          5.0
14                 'nun': 'monk',                          5.0
15    'obstetrics': 'gynecology',                          2.0
16                  'her': 'his',                          5.0
17         'marchioness': 'thun',                          0.0
18             'mare': 'gelding',                          3.0
19        'convent': 'monastery',                          5.0
20   'priestesses': 'courtesans',                          0.0
21               'queen': 'king',                          5.0
22              'gals': 'buzzard'                          1.0

    debias_2_make_sense_peiyu  debias_2_make_sense_luming
0                         5.0                         5.0
1                         5.0                         5.0
2                         5.0                         5.0
3                         2.0                         1.0
4                         5.0                         5.0
5                         0.0                         0.0
6                         0.0                         0.0
7                         5.0                         5.0
8                         0.0                         0.0
9                         5.0                         5.0
10                        0.0                         1.0
11                        5.0                         5.0
12                        5.0                         5.0
13                        5.0                         5.0
14                        5.0                         5.0
15                        3.0                         2.0
16                        5.0                         5.0
17                        0.0                         0.0
18                        4.0                         0.0
19                        5.0                         5.0
20                        0.0                         0.0
21                        5.0                         5.0
22                        2.0                         0.0
6
3.0

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [207]:
questions=np.arange(1,len(debias_2_nn)+1)
#questions
zero_lst=[]
one_lst=[]
two_lst=[]
three_lst=[]
four_lst=[]
five_lst=[]
for i in range(len(debias_2_nn)):
    scores=debias_2_nn.iloc[i,1:4]
    zero_lst.append(len(scores[scores==0]))
    one_lst.append(len(scores[scores==1]))
    two_lst.append(len(scores[scores==2]))
    three_lst.append(len(scores[scores==3]))
    four_lst.append(len(scores[scores==4]))
    five_lst.append(len(scores[scores==5]))
print(len(zero_lst))
inter_coder=pd.DataFrame(list(zip(questions,zero_lst,one_lst,two_lst,three_lst,four_lst,five_lst)),columns = ['q_num','0', '1','2','3','4','5'])
inter_coder.set_index('q_num',inplace=True)
inter_coder

23

       0  1  2  3  4  5
q_num
1      0  0  0  0  0  3
2      0  0  0  0  0  3
3      0  0  0  0  0  3
4      0  1  2  0  0  0
5      0  0  0  0  0  3
6      3  0  0  0  0  0
7      3  0  0  0  0  0
8      0  0  0  0  0  3
9      3  0  0  0  0  0
10     0  0  0  0  0  3
11     2  1  0  0  0  0
12     0  0  0  0  0  3
13     0  0  0  0  0  3
14     0  0  0  0  0  3
15     0  0  0  0  0  3
16     0  0  2  1  0  0
17     0  0  0  0  0  3
18     3  0  0  0  0  0
19     1  0  0  1  1  0
20     0  0  0  0  0  3
21     3  0  0  0  0  0
22     0  0  0  0  0  3
23     1  1  1  0  0  0

In [208]:
path='inter_coder.xlsx'
writer = pd.ExcelWriter(path, engine = 'xlsxwriter')
inter_coder.to_excel(writer, sheet_name = 'inter_code_2')
writer.save()
writer.close()

In [116]:
debias_2_merge=debias_2[['debiased_2','avg_score_2']]
#print(debias_2_merge)
debias_2_merge['on']=debias_2_merge.debiased_2.str.split(':').str[0]
print(debias_2_merge)

                       debiased_2  avg_score_2              on
0           'mothers': 'fathers',         5.00       'mothers'
1             'actress': 'actor',         5.00       'actress'
2                 'mama': 'papa',         5.00          'mama'
3    'menopause': 'menstruation',         1.67     'menopause'
4           'princess': 'prince',         5.00      'princess'
5    'governesses': 'courtesans',         0.00   'governesses'
6              'abbess': 'fulda',         0.00        'abbess'
7                 'women': 'men',         5.00         'women'
8           'widow': 'zarephath',         0.00         'widow'
9          'ladies': 'gentlemen',         5.00        'ladies'
10      'baroness': 'courtesans',         0.00      'baroness'
11             'niece': 'nephew',         5.00         'niece'
12           'lady': 'gentleman',         5.00          'lady'
13           'sister': 'brother',         5.00        'sister'
14                 'nun': 'monk',         5.00           'nun'
15    'obstetrics': 'gynecology',         2.67    'obstetrics'
16                  'her': 'his',         5.00           'her'
17         'marchioness': 'thun',         0.00   'marchioness'
18             'mare': 'gelding',         0.00          'mare'
19        'convent': 'monastery',         5.00       'convent'
20   'priestesses': 'courtesans',         0.00   'priestesses'
21               'queen': 'king',         5.00         'queen'
22              'gals': 'buzzard'         0.00          'gals'

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [166]:
debias_3=df.iloc[:,15:20]
debias_3.drop(columns=['debias_3_make_sense_wei'],inplace=True)
debias_3

,debiased_3,debias_3_make_sense_farhana,debias_3_make_sense_peiyu,debias_3_make_sense_luming
0,"'maidservant': 'manservant',",5.0,5.0,5.0
1,"'mama': 'mom',",1.0,1.0,1.0
2,"'clitoris': 'penis',",5.0,5.0,5.0
3,"'governesses': 'winfred',",0.0,0.0,0.0
4,"'abbess': 'bingen',",0.0,0.0,0.0
5,"'women': 'men',",5.0,5.0,5.0
6,"'widow': 'daughter',",1.0,2.0,1.0
7,"'ladies': 'lady',",2.0,1.0,1.0
8,"'brides': 'heroics',",3.0,3.0,2.0
9,"'baroness': 'missus',",0.0,2.0,1.0
10,"'niece': 'lady',",3.0,2.0,1.0
11,"'widows': 'orphans',",4.0,4.0,3.0
12,"'lady': 'woman',",2.0,2.0,1.0
13,"'sister': 'granddaughter',",2.0,2.0,2.0
14,"'obstetrics': 'gynecology',",2.0,2.0,2.0
15,"'her': 'he',",5.0,5.0,5.0
16,"'marchioness': 'egeland',",0.0,0.0,0.0
17,"'mare': 'gelding',",4.0,4.0,0.0
18,"'priestesses': 'democratique',",3.0,3.0,5.0
19,'queen': 'queens',2.0,2.0,2.0
20,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN

In [172]:
debias_3_all=debias_3.fillna(0)
print(debias_3_all)

zero_count_3_all=0
for i in range(len(debias_3_all)):
    scores=debias_3_all.iloc[i,1:]
    if len(scores[scores==0])>=2:
        zero_count_3_all+=1
        
print(zero_count_3_all)
debias_3_all['avg_score_3_all']=0
for i in range(len(debias_3_all)):
    scores=debias_3_all.iloc[i,1:]
    if len(scores[scores==0])<2:
        debias_3_all.iloc[i,4]=round(sum(debias_3_all.iloc[i,1:4])/3,2)
debias_3_all

print(sum(debias_3_all.iloc[:,4])/len(debias_3_all.iloc[:,4]))

                         debiased_3  debias_3_make_sense_farhana  \
0      'maidservant': 'manservant',                          5.0
1                    'mama': 'mom',                          1.0
2              'clitoris': 'penis',                          5.0
3         'governesses': 'winfred',                          0.0
4               'abbess': 'bingen',                          0.0
5                   'women': 'men',                          5.0
6              'widow': 'daughter',                          1.0
7                 'ladies': 'lady',                          2.0
8              'brides': 'heroics',                          3.0
9             'baroness': 'missus',                          0.0
10                 'niece': 'lady',                          3.0
11             'widows': 'orphans',                          4.0
12                 'lady': 'woman',                          2.0
13       'sister': 'granddaughter',                          2.0
14      'obstetrics': 'gynecology',                          2.0
15                     'her': 'he',                          5.0
16        'marchioness': 'egeland',                          0.0
17               'mare': 'gelding',                          4.0
18   'priestesses': 'democratique',                          3.0
19                'queen': 'queens'                          2.0
20                                0                          0.0
21                                0                          0.0
22                                0                          0.0
23                                0                          0.0
24                                0                          0.0
25                                0                          0.0
26                                0                          0.0
27                                0                          0.0
28                                0                          0.0
29                                0                          0.0
30                                0                          0.0
31                                0                          0.0
32                                0                          0.0
33                                0                          0.0
34                                0                          0.0
35                                0                          0.0
36                                0                          0.0
37                                0                          0.0
38                                0                          0.0
39                                0                          0.0
40                                0                          0.0
41                                0                          0.0
42                                0                          0.0

    debias_3_make_sense_peiyu  debias_3_make_sense_luming
0                         5.0                         5.0
1                         1.0                         1.0
2                         5.0                         5.0
3                         0.0                         0.0
4                         0.0                         0.0
5                         5.0                         5.0
6                         2.0                         1.0
7                         1.0                         1.0
8                         3.0                         2.0
9                         2.0                         1.0
10                        2.0                         1.0
11                        4.0                         3.0
12                        2.0                         1.0
13                        2.0                         2.0
14                        2.0                         2.0
15                        5.0                         5.0
16                        0.0                         0.0
17                        4.0                         0.0
18                        3.0                         5.0
19                        2.0                         2.0
20                        0.0                         0.0
21                        0.0                         0.0
22                        0.0                         0.0
23                        0.0                         0.0
24                        0.0                         0.0
25                        0.0                         0.0
26                        0.0                         0.0
27                        0.0                         0.0
28                        0.0                         0.0
29                        0.0                         0.0
30                        0.0                         0.0
31                        0.0                         0.0
32                        0.0                         0.0
33                        0.0                         0.0
34                        0.0                         0.0
35                        0.0                         0.0
36                        0.0                         0.0
37                        0.0                         0.0
38                        0.0                         0.0
39                        0.0                         0.0
40                        0.0                         0.0
41                        0.0                         0.0
42                        0.0                         0.0
26
1.0079069767441862

In [167]:
debias_3_nn=debias_3.dropna()
print(debias_3_nn)
zero_count_3_nn=0
for i in range(len(debias_3_nn)):
    scores=debias_3_nn.iloc[i,1:]
    if len(scores[scores==0])>=2:
        zero_count_3_nn+=1
        
print(zero_count_3_nn)
debias_3_nn['avg_score_3_nn']=0
for i in range(len(debias_3_nn)):
    scores=debias_3_nn.iloc[i,1:]
    if len(scores[scores==0])<2:
        debias_3_nn.iloc[i,4]=round(sum(debias_3_nn.iloc[i,1:4])/3,2)
debias_3_nn

print(sum(debias_3_nn.iloc[:,4])/len(debias_3_nn.iloc[:,4]))

                         debiased_3  debias_3_make_sense_farhana  \
0      'maidservant': 'manservant',                          5.0
1                    'mama': 'mom',                          1.0
2              'clitoris': 'penis',                          5.0
3         'governesses': 'winfred',                          0.0
4               'abbess': 'bingen',                          0.0
5                   'women': 'men',                          5.0
6              'widow': 'daughter',                          1.0
7                 'ladies': 'lady',                          2.0
8              'brides': 'heroics',                          3.0
9             'baroness': 'missus',                          0.0
10                 'niece': 'lady',                          3.0
11             'widows': 'orphans',                          4.0
12                 'lady': 'woman',                          2.0
13       'sister': 'granddaughter',                          2.0
14      'obstetrics': 'gynecology',                          2.0
15                     'her': 'he',                          5.0
16        'marchioness': 'egeland',                          0.0
17               'mare': 'gelding',                          4.0
18   'priestesses': 'democratique',                          3.0
19                'queen': 'queens'                          2.0

    debias_3_make_sense_peiyu  debias_3_make_sense_luming
0                         5.0                         5.0
1                         1.0                         1.0
2                         5.0                         5.0
3                         0.0                         0.0
4                         0.0                         0.0
5                         5.0                         5.0
6                         2.0                         1.0
7                         1.0                         1.0
8                         3.0                         2.0
9                         2.0                         1.0
10                        2.0                         1.0
11                        4.0                         3.0
12                        2.0                         1.0
13                        2.0                         2.0
14                        2.0                         2.0
15                        5.0                         5.0
16                        0.0                         0.0
17                        4.0                         0.0
18                        3.0                         5.0
19                        2.0                         2.0
3
2.1670000000000003

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [209]:
questions=np.arange(1,len(debias_3_nn)+1)
#questions
zero_lst=[]
one_lst=[]
two_lst=[]
three_lst=[]
four_lst=[]
five_lst=[]
for i in range(len(debias_3_nn)):
    scores=debias_3_nn.iloc[i,1:4]
    zero_lst.append(len(scores[scores==0]))
    one_lst.append(len(scores[scores==1]))
    two_lst.append(len(scores[scores==2]))
    three_lst.append(len(scores[scores==3]))
    four_lst.append(len(scores[scores==4]))
    five_lst.append(len(scores[scores==5]))
print(len(zero_lst))
inter_coder=pd.DataFrame(list(zip(questions,zero_lst,one_lst,two_lst,three_lst,four_lst,five_lst)),columns = ['q_num','0', '1','2','3','4','5'])
inter_coder.set_index('q_num',inplace=True)
inter_coder

20

       0  1  2  3  4  5
q_num
1      0  0  0  0  0  3
2      0  3  0  0  0  0
3      0  0  0  0  0  3
4      3  0  0  0  0  0
5      3  0  0  0  0  0
6      0  0  0  0  0  3
7      0  2  1  0  0  0
8      0  2  1  0  0  0
9      0  0  1  2  0  0
10     1  1  1  0  0  0
11     0  1  1  1  0  0
12     0  0  0  1  2  0
13     0  1  2  0  0  0
14     0  0  3  0  0  0
15     0  0  3  0  0  0
16     0  0  0  0  0  3
17     3  0  0  0  0  0
18     1  0  0  0  2  0
19     0  0  0  2  0  1
20     0  0  3  0  0  0

In [210]:
path='inter_coder.xlsx'
writer = pd.ExcelWriter(path, engine = 'xlsxwriter')
inter_coder.to_excel(writer, sheet_name = 'inter_code_3')
writer.save()
writer.close()

In [119]:
debias_3_merge=debias_3[['debiased_3','avg_score_3']]
print(debias_3_merge)

debias_3_merge['on']=debias_3_merge.debiased_3.str.split(':').str[0]
print(debias_3_merge)

                         debiased_3  avg_score_3
0      'maidservant': 'manservant',         5.00
1                    'mama': 'mom',         1.00
2              'clitoris': 'penis',         5.00
3         'governesses': 'winfred',         0.00
4               'abbess': 'bingen',         0.00
5                   'women': 'men',         5.00
6              'widow': 'daughter',         1.67
7                 'ladies': 'lady',         1.00
8              'brides': 'heroics',         2.67
9             'baroness': 'missus',         1.67
10                 'niece': 'lady',         1.67
11             'widows': 'orphans',         3.67
12                 'lady': 'woman',         1.67
13       'sister': 'granddaughter',         2.00
14      'obstetrics': 'gynecology',         2.00
15                     'her': 'he',         5.00
16        'marchioness': 'egeland',         0.00
17               'mare': 'gelding',         0.00
18   'priestesses': 'democratique',         3.67
19                'queen': 'queens'         2.00
                         debiased_3  avg_score_3              on
0      'maidservant': 'manservant',         5.00   'maidservant'
1                    'mama': 'mom',         1.00          'mama'
2              'clitoris': 'penis',         5.00      'clitoris'
3         'governesses': 'winfred',         0.00   'governesses'
4               'abbess': 'bingen',         0.00        'abbess'
5                   'women': 'men',         5.00         'women'
6              'widow': 'daughter',         1.67         'widow'
7                 'ladies': 'lady',         1.00        'ladies'
8              'brides': 'heroics',         2.67        'brides'
9             'baroness': 'missus',         1.67      'baroness'
10                 'niece': 'lady',         1.67         'niece'
11             'widows': 'orphans',         3.67        'widows'
12                 'lady': 'woman',         1.67          'lady'
13       'sister': 'granddaughter',         2.00        'sister'
14      'obstetrics': 'gynecology',         2.00    'obstetrics'
15                     'her': 'he',         5.00           'her'
16        'marchioness': 'egeland',         0.00   'marchioness'
17               'mare': 'gelding',         0.00          'mare'
18   'priestesses': 'democratique',         3.67   'priestesses'
19                'queen': 'queens'         2.00         'queen'

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [171]:
debias_4=df.iloc[:,20:25]
debias_4.drop(columns=['debias_4_make_sense_wei'],inplace=True)
debias_4

,debiased_4,debias_4_make_sense_farhana,debias_4_make_sense_peiyu,debias_4_make_sense_luming
0,"'maidservant': 'manservant',",5.0,5.0,5.0
1,"'mama': 'mom',",1.0,1.0,1.0
2,"'clitoris': 'penis',",5.0,5.0,5.0
3,"'governesses': 'courtesans',",0.0,0.0,0.0
4,"'abbess': 'josselin',",0.0,0.0,0.0
5,"'women': 'men',",5.0,5.0,5.0
6,"'widow': 'daughter',",1.0,2.0,1.0
7,"'ladies': 'lady',",2.0,2.0,1.0
8,"'brides': 'heroics',",3.0,3.0,2.0
9,"'baroness': 'missus',",2.0,2.0,1.0
10,"'niece': 'granddaughter',",2.0,2.0,1.0
11,"'sister': 'granddaughter',",2.0,2.0,1.0
12,"'obstetrics': 'gynecology',",1.0,2.0,2.0
13,"'her': 'his',",5.0,5.0,5.0
14,"'marchioness': 'mungo',",0.0,0.0,0.0
15,"'mare': 'gelding',",2.0,4.0,0.0
16,"'priestesses': 'courtesans',",0.0,0.0,0.0
17,'queen': 'queens',2.0,2.0,2.0
18,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN

In [173]:
debias_4_all=debias_4.fillna(0)
print(debias_4_all)

zero_count_4_all=0
for i in range(len(debias_4_all)):
    scores=debias_4_all.iloc[i,1:]
    if len(scores[scores==0])>=2:
        zero_count_4_all+=1
        
print(zero_count_4_all)
debias_4_all['avg_score_4_all']=0
for i in range(len(debias_4_all)):
    scores=debias_4_all.iloc[i,1:]
    if len(scores[scores==0])<2:
        debias_4_all.iloc[i,4]=round(sum(debias_4_all.iloc[i,1:4])/3,2)
debias_4_all

print(sum(debias_4_all.iloc[:,4])/len(debias_4_all.iloc[:,4]))

                       debiased_4  debias_4_make_sense_farhana  \
0    'maidservant': 'manservant',                          5.0
1                  'mama': 'mom',                          1.0
2            'clitoris': 'penis',                          5.0
3    'governesses': 'courtesans',                          0.0
4           'abbess': 'josselin',                          0.0
5                 'women': 'men',                          5.0
6            'widow': 'daughter',                          1.0
7               'ladies': 'lady',                          2.0
8            'brides': 'heroics',                          3.0
9           'baroness': 'missus',                          2.0
10      'niece': 'granddaughter',                          2.0
11     'sister': 'granddaughter',                          2.0
12    'obstetrics': 'gynecology',                          1.0
13                  'her': 'his',                          5.0
14        'marchioness': 'mungo',                          0.0
15             'mare': 'gelding',                          2.0
16   'priestesses': 'courtesans',                          0.0
17              'queen': 'queens'                          2.0
18                              0                          0.0
19                              0                          0.0
20                              0                          0.0
21                              0                          0.0
22                              0                          0.0
23                              0                          0.0
24                              0                          0.0
25                              0                          0.0
26                              0                          0.0
27                              0                          0.0
28                              0                          0.0
29                              0                          0.0
30                              0                          0.0
31                              0                          0.0
32                              0                          0.0
33                              0                          0.0
34                              0                          0.0
35                              0                          0.0
36                              0                          0.0
37                              0                          0.0
38                              0                          0.0
39                              0                          0.0
40                              0                          0.0
41                              0                          0.0
42                              0                          0.0

    debias_4_make_sense_peiyu  debias_4_make_sense_luming
0                         5.0                         5.0
1                         1.0                         1.0
2                         5.0                         5.0
3                         0.0                         0.0
4                         0.0                         0.0
5                         5.0                         5.0
6                         2.0                         1.0
7                         2.0                         1.0
8                         3.0                         2.0
9                         2.0                         1.0
10                        2.0                         1.0
11                        2.0                         1.0
12                        2.0                         2.0
13                        5.0                         5.0
14                        0.0                         0.0
15                        4.0                         0.0
16                        0.0                         0.0
17                        2.0                         2.0
18                        0.0                         0.0
19                        0.0                         0.0
20                        0.0                         0.0
21                        0.0                         0.0
22                        0.0                         0.0
23                        0.0                         0.0
24                        0.0                         0.0
25                        0.0                         0.0
26                        0.0                         0.0
27                        0.0                         0.0
28                        0.0                         0.0
29                        0.0                         0.0
30                        0.0                         0.0
31                        0.0                         0.0
32                        0.0                         0.0
33                        0.0                         0.0
34                        0.0                         0.0
35                        0.0                         0.0
36                        0.0                         0.0
37                        0.0                         0.0
38                        0.0                         0.0
39                        0.0                         0.0
40                        0.0                         0.0
41                        0.0                         0.0
42                        0.0                         0.0
29
0.8220930232558141

In [174]:
debias_4_nn=debias_4.dropna()
print(debias_4_nn)
zero_count_4_nn=0
for i in range(len(debias_4_nn)):
    scores=debias_4_nn.iloc[i,1:]
    if len(scores[scores==0])>=2:
        zero_count_4_nn+=1
        
print(zero_count_4_nn)
debias_4_nn['avg_score_4_nn']=0
for i in range(len(debias_4_nn)):
    scores=debias_4_nn.iloc[i,1:]
    if len(scores[scores==0])<2:
        debias_4_nn.iloc[i,4]=round(sum(debias_4_nn.iloc[i,1:4])/3,2)
debias_4_nn

print(sum(debias_4_nn.iloc[:,4])/len(debias_4_nn.iloc[:,4]))

                       debiased_4  debias_4_make_sense_farhana  \
0    'maidservant': 'manservant',                          5.0
1                  'mama': 'mom',                          1.0
2            'clitoris': 'penis',                          5.0
3    'governesses': 'courtesans',                          0.0
4           'abbess': 'josselin',                          0.0
5                 'women': 'men',                          5.0
6            'widow': 'daughter',                          1.0
7               'ladies': 'lady',                          2.0
8            'brides': 'heroics',                          3.0
9           'baroness': 'missus',                          2.0
10      'niece': 'granddaughter',                          2.0
11     'sister': 'granddaughter',                          2.0
12    'obstetrics': 'gynecology',                          1.0
13                  'her': 'his',                          5.0
14        'marchioness': 'mungo',                          0.0
15             'mare': 'gelding',                          2.0
16   'priestesses': 'courtesans',                          0.0
17              'queen': 'queens'                          2.0

    debias_4_make_sense_peiyu  debias_4_make_sense_luming
0                         5.0                         5.0
1                         1.0                         1.0
2                         5.0                         5.0
3                         0.0                         0.0
4                         0.0                         0.0
5                         5.0                         5.0
6                         2.0                         1.0
7                         2.0                         1.0
8                         3.0                         2.0
9                         2.0                         1.0
10                        2.0                         1.0
11                        2.0                         1.0
12                        2.0                         2.0
13                        5.0                         5.0
14                        0.0                         0.0
15                        4.0                         0.0
16                        0.0                         0.0
17                        2.0                         2.0
4
1.9638888888888895

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [211]:
questions=np.arange(1,len(debias_4_nn)+1)
#questions
zero_lst=[]
one_lst=[]
two_lst=[]
three_lst=[]
four_lst=[]
five_lst=[]
for i in range(len(debias_4_nn)):
    scores=debias_4_nn.iloc[i,1:4]
    zero_lst.append(len(scores[scores==0]))
    one_lst.append(len(scores[scores==1]))
    two_lst.append(len(scores[scores==2]))
    three_lst.append(len(scores[scores==3]))
    four_lst.append(len(scores[scores==4]))
    five_lst.append(len(scores[scores==5]))
print(len(zero_lst))
inter_coder=pd.DataFrame(list(zip(questions,zero_lst,one_lst,two_lst,three_lst,four_lst,five_lst)),columns = ['q_num','0', '1','2','3','4','5'])
inter_coder.set_index('q_num',inplace=True)
inter_coder

18

       0  1  2  3  4  5
q_num
1      0  0  0  0  0  3
2      0  3  0  0  0  0
3      0  0  0  0  0  3
4      3  0  0  0  0  0
5      3  0  0  0  0  0
6      0  0  0  0  0  3
7      0  2  1  0  0  0
8      0  1  2  0  0  0
9      0  0  1  2  0  0
10     0  1  2  0  0  0
11     0  1  2  0  0  0
12     0  1  2  0  0  0
13     0  1  2  0  0  0
14     0  0  0  0  0  3
15     3  0  0  0  0  0
16     1  0  1  0  1  0
17     3  0  0  0  0  0
18     0  0  3  0  0  0

In [212]:
path='inter_coder.xlsx'
writer = pd.ExcelWriter(path, engine = 'xlsxwriter')
inter_coder.to_excel(writer, sheet_name = 'inter_code_4')
writer.save()
writer.close()

In [122]:
"""debias_4_merge=debias_4[['debiased_4','avg_score_4']]
print(debias_4_merge)
debias_4_merge['on']=debias_4_merge.debiased_4.str.split(':').str[0]
print(debias_4_merge)"""

                       debiased_4  avg_score_4
0    'maidservant': 'manservant',         5.00
1                  'mama': 'mom',         1.00
2            'clitoris': 'penis',         5.00
3    'governesses': 'courtesans',         0.00
4           'abbess': 'josselin',         0.00
5                 'women': 'men',         5.00
6            'widow': 'daughter',         1.67
7               'ladies': 'lady',         1.67
8            'brides': 'heroics',         2.67
9           'baroness': 'missus',         1.67
10      'niece': 'granddaughter',         1.67
11     'sister': 'granddaughter',         1.67
12    'obstetrics': 'gynecology',         2.00
13                  'her': 'his',         5.00
14        'marchioness': 'mungo',         0.00
15             'mare': 'gelding',         0.00
16   'priestesses': 'courtesans',         0.00
17              'queen': 'queens'         2.00
                       debiased_4  avg_score_4              on
0    'maidservant': 'manservant',         5.00   'maidservant'
1                  'mama': 'mom',         1.00          'mama'
2            'clitoris': 'penis',         5.00      'clitoris'
3    'governesses': 'courtesans',         0.00   'governesses'
4           'abbess': 'josselin',         0.00        'abbess'
5                 'women': 'men',         5.00         'women'
6            'widow': 'daughter',         1.67         'widow'
7               'ladies': 'lady',         1.67        'ladies'
8            'brides': 'heroics',         2.67        'brides'
9           'baroness': 'missus',         1.67      'baroness'
10      'niece': 'granddaughter',         1.67         'niece'
11     'sister': 'granddaughter',         1.67        'sister'
12    'obstetrics': 'gynecology',         2.00    'obstetrics'
13                  'her': 'his',         5.00           'her'
14        'marchioness': 'mungo',         0.00   'marchioness'
15             'mare': 'gelding',         0.00          'mare'
16   'priestesses': 'courtesans',         0.00   'priestesses'
17              'queen': 'queens'         2.00         'queen'

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [176]:
debias_5=df.iloc[:,25:]
debias_5.drop(columns=['debias_5_make_sense_wei'],inplace=True)
debias_5
#debias_5.fillna(0,inplace=True)
#debias_5

,debiased_5,debias_5_make_sense_farhana,debias_5_make_sense_peiyu,debias_5_make_sense_luming
0,"'maidservant': 'manservant',",5.0,5.0,5.0
1,"'mama': 'mom',",1.0,2.0,1.0
2,"'clitoris': 'penis',",5.0,5.0,5.0
3,"'governesses': 'courtesans',",0.0,0.0,0.0
4,"'abbess': 'fulda',",0.0,0.0,0.0
5,"'widow': 'son',",4.0,3.0,4.0
6,"'ladies': 'lady',",2.0,2.0,1.0
7,"'brides': 'heroics',",4.0,3.0,2.0
8,"'baroness': 'missus',",2.0,2.0,2.0
9,"'niece': 'granddaughter',",1.0,2.0,2.0
10,"'widows': 'orphans',",2.0,2.0,3.0
11,"'sister': 'granddaughter',",2.0,2.0,2.0
12,"'her': 'he',",5.0,5.0,5.0
13,"'marchioness': 'blessington',",0.0,0.0,0.0
14,"'priestesses': 'courtesans',",0.0,0.0,0.0
15,'queen': 'queens',1.0,2.0,2.0
16,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN
23,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN
26,NaN,NaN,NaN,NaN
27,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN
41,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN

In [177]:
debias_5_all=debias_5.fillna(0)
print(debias_5_all)

zero_count_5_all=0
for i in range(len(debias_5_all)):
    scores=debias_5_all.iloc[i,1:]
    if len(scores[scores==0])>=2:
        zero_count_5_all+=1
        
print(zero_count_5_all)
debias_5_all['avg_score_5_all']=0
for i in range(len(debias_5_all)):
    scores=debias_5_all.iloc[i,1:]
    if len(scores[scores==0])<2:
        debias_5_all.iloc[i,4]=round(sum(debias_5_all.iloc[i,1:4])/3,2)
debias_5_all

print(sum(debias_5_all.iloc[:,4])/len(debias_5_all.iloc[:,4]))

                        debiased_5  debias_5_make_sense_farhana  \
0     'maidservant': 'manservant',                          5.0
1                   'mama': 'mom',                          1.0
2             'clitoris': 'penis',                          5.0
3     'governesses': 'courtesans',                          0.0
4               'abbess': 'fulda',                          0.0
5                  'widow': 'son',                          4.0
6                'ladies': 'lady',                          2.0
7             'brides': 'heroics',                          4.0
8            'baroness': 'missus',                          2.0
9        'niece': 'granddaughter',                          1.0
10            'widows': 'orphans',                          2.0
11      'sister': 'granddaughter',                          2.0
12                    'her': 'he',                          5.0
13   'marchioness': 'blessington',                          0.0
14    'priestesses': 'courtesans',                          0.0
15               'queen': 'queens'                          1.0
16                               0                          0.0
17                               0                          0.0
18                               0                          0.0
19                               0                          0.0
20                               0                          0.0
21                               0                          0.0
22                               0                          0.0
23                               0                          0.0
24                               0                          0.0
25                               0                          0.0
26                               0                          0.0
27                               0                          0.0
28                               0                          0.0
29                               0                          0.0
30                               0                          0.0
31                               0                          0.0
32                               0                          0.0
33                               0                          0.0
34                               0                          0.0
35                               0                          0.0
36                               0                          0.0
37                               0                          0.0
38                               0                          0.0
39                               0                          0.0
40                               0                          0.0
41                               0                          0.0
42                               0                          0.0

    debias_5_make_sense_peiyu  debias_5_make_sense_luming
0                         5.0                         5.0
1                         2.0                         1.0
2                         5.0                         5.0
3                         0.0                         0.0
4                         0.0                         0.0
5                         3.0                         4.0
6                         2.0                         1.0
7                         3.0                         2.0
8                         2.0                         2.0
9                         2.0                         2.0
10                        2.0                         3.0
11                        2.0                         2.0
12                        5.0                         5.0
13                        0.0                         0.0
14                        0.0                         0.0
15                        2.0                         2.0
16                        0.0                         0.0
17                        0.0                         0.0
18                        0.0                         0.0
19                        0.0                         0.0
20                        0.0                         0.0
21                        0.0                         0.0
22                        0.0                         0.0
23                        0.0                         0.0
24                        0.0                         0.0
25                        0.0                         0.0
26                        0.0                         0.0
27                        0.0                         0.0
28                        0.0                         0.0
29                        0.0                         0.0
30                        0.0                         0.0
31                        0.0                         0.0
32                        0.0                         0.0
33                        0.0                         0.0
34                        0.0                         0.0
35                        0.0                         0.0
36                        0.0                         0.0
37                        0.0                         0.0
38                        0.0                         0.0
39                        0.0                         0.0
40                        0.0                         0.0
41                        0.0                         0.0
42                        0.0                         0.0
31
0.7986046511627908

In [178]:
debias_5_nn=debias_5.dropna()
print(debias_5_nn)
zero_count_5_nn=0
for i in range(len(debias_5_nn)):
    scores=debias_5_nn.iloc[i,1:]
    if len(scores[scores==0])>=2:
        zero_count_5_nn+=1
        
print(zero_count_5_nn)
debias_5_nn['avg_score_5_nn']=0
for i in range(len(debias_5_nn)):
    scores=debias_5_nn.iloc[i,1:]
    if len(scores[scores==0])<2:
        debias_5_nn.iloc[i,4]=round(sum(debias_5_nn.iloc[i,1:4])/3,2)
debias_5_nn

print(sum(debias_5_nn.iloc[:,4])/len(debias_5_nn.iloc[:,4]))

                        debiased_5  debias_5_make_sense_farhana  \
0     'maidservant': 'manservant',                          5.0
1                   'mama': 'mom',                          1.0
2             'clitoris': 'penis',                          5.0
3     'governesses': 'courtesans',                          0.0
4               'abbess': 'fulda',                          0.0
5                  'widow': 'son',                          4.0
6                'ladies': 'lady',                          2.0
7             'brides': 'heroics',                          4.0
8            'baroness': 'missus',                          2.0
9        'niece': 'granddaughter',                          1.0
10            'widows': 'orphans',                          2.0
11      'sister': 'granddaughter',                          2.0
12                    'her': 'he',                          5.0
13   'marchioness': 'blessington',                          0.0
14    'priestesses': 'courtesans',                          0.0
15               'queen': 'queens'                          1.0

    debias_5_make_sense_peiyu  debias_5_make_sense_luming
0                         5.0                         5.0
1                         2.0                         1.0
2                         5.0                         5.0
3                         0.0                         0.0
4                         0.0                         0.0
5                         3.0                         4.0
6                         2.0                         1.0
7                         3.0                         2.0
8                         2.0                         2.0
9                         2.0                         2.0
10                        2.0                         3.0
11                        2.0                         2.0
12                        5.0                         5.0
13                        0.0                         0.0
14                        0.0                         0.0
15                        2.0                         2.0
4
2.14625

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.

In [213]:
questions=np.arange(1,len(debias_5_nn)+1)
#questions
zero_lst=[]
one_lst=[]
two_lst=[]
three_lst=[]
four_lst=[]
five_lst=[]
for i in range(len(debias_5_nn)):
    scores=debias_5_nn.iloc[i,1:4]
    zero_lst.append(len(scores[scores==0]))
    one_lst.append(len(scores[scores==1]))
    two_lst.append(len(scores[scores==2]))
    three_lst.append(len(scores[scores==3]))
    four_lst.append(len(scores[scores==4]))
    five_lst.append(len(scores[scores==5]))
print(len(zero_lst))
inter_coder=pd.DataFrame(list(zip(questions,zero_lst,one_lst,two_lst,three_lst,four_lst,five_lst)),columns = ['q_num','0', '1','2','3','4','5'])
inter_coder.set_index('q_num',inplace=True)
inter_coder

16

       0  1  2  3  4  5
q_num
1      0  0  0  0  0  3
2      0  2  1  0  0  0
3      0  0  0  0  0  3
4      3  0  0  0  0  0
5      3  0  0  0  0  0
6      0  0  0  1  2  0
7      0  1  2  0  0  0
8      0  0  1  1  1  0
9      0  0  3  0  0  0
10     0  1  2  0  0  0
11     0  0  2  1  0  0
12     0  0  3  0  0  0
13     0  0  0  0  0  3
14     3  0  0  0  0  0
15     3  0  0  0  0  0
16     0  1  2  0  0  0

In [214]:
path='inter_coder.xlsx'
writer = pd.ExcelWriter(path, engine = 'xlsxwriter')
inter_coder.to_excel(writer, sheet_name = 'inter_code_5')
writer.save()
writer.close()

In [125]:
debias_5_merge=debias_5[['debiased_5','avg_score_5']]
print(debias_5_merge)
debias_5_merge['on']=debias_5_merge.debiased_5.str.split(':').str[0]
print(debias_5_merge)

                        debiased_5  avg_score_5
0     'maidservant': 'manservant',         5.00
1                   'mama': 'mom',         1.67
2             'clitoris': 'penis',         5.00
3     'governesses': 'courtesans',         0.00
4               'abbess': 'fulda',         0.00
5                  'widow': 'son',         3.33
6                'ladies': 'lady',         1.67
7             'brides': 'heroics',         2.67
8            'baroness': 'missus',         2.00
9        'niece': 'granddaughter',         2.00
10            'widows': 'orphans',         2.33
11      'sister': 'granddaughter',         2.00
12                    'her': 'he',         5.00
13   'marchioness': 'blessington',         0.00
14    'priestesses': 'courtesans',         0.00
15               'queen': 'queens'         2.00
                        debiased_5  avg_score_5              on
0     'maidservant': 'manservant',         5.00   'maidservant'
1                   'mama': 'mom',         1.67          'mama'
2             'clitoris': 'penis',         5.00      'clitoris'
3     'governesses': 'courtesans',         0.00   'governesses'
4               'abbess': 'fulda',         0.00        'abbess'
5                  'widow': 'son',         3.33         'widow'
6                'ladies': 'lady',         1.67        'ladies'
7             'brides': 'heroics',         2.67        'brides'
8            'baroness': 'missus',         2.00      'baroness'
9        'niece': 'granddaughter',         2.00         'niece'
10            'widows': 'orphans',         2.33        'widows'
11      'sister': 'granddaughter',         2.00        'sister'
12                    'her': 'he',         5.00           'her'
13   'marchioness': 'blessington',         0.00   'marchioness'
14    'priestesses': 'courtesans',         0.00   'priestesses'
15               'queen': 'queens'         2.00         'queen'

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [126]:
original_d1=original_merge.merge(debias_1_merge,how='left',left_on='on',right_on='on')
print(original_d1)

                                original  avg_score_o                on  \
0                  maidservant': 'susa',         1.33     'maidservant'
1                    'actress': 'actor',         5.00         'actress'
2                        'mama': 'yeah',         0.00            'mama'
3                'clitoris': 'frenulum',         0.00        'clitoris'
4             'princess': 'casamassima',         0.00        'princess'
5               'governesses': 'platon',         0.00     'governesses'
6                     'abbess': 'fulda',         0.00          'abbess'
7                        'women': 'men',         5.00           'women'
8                  'widow': 'zarephath',         0.00           'widow'
9                 'ladies': 'gentlemen',         5.00          'ladies'
10                       'madam': 'sir',         5.00           'madam'
11                  'baroness': 'spaak',         0.00        'baroness'
12                    'niece': 'nephew',         5.00           'niece'
13                  'widows': 'orphans',         0.00          'widows'
14                  'lady': 'gentleman',         5.00            'lady'
15                  'sister': 'brother',         5.00          'sister'
16                        'nun': 'monk',         5.00             'nun'
17          'obstetrics': 'gynaecology',         1.67      'obstetrics'
18                          'her': 'he',         5.00             'her'
19                 'marchioness': 'kom',         0.00     'marchioness'
20               'convent': 'monastery',         0.00         'convent'
21         'priestesses': 'darstellung',         0.00     'priestesses'
22                      'queen': 'king',         5.00           'queen'
23                 'empress': 'emperor',         5.00         'empress'
24                     'mommy': 'daddy',         5.00           'mommy'
25        'enchantress': 'relinquishes',         1.67     'enchantress'
26               'estrogen': 'androgen',         5.00        'estrogen'
27                    'goddess': 'gods',         5.00         'goddess'
28                     'aunt': 'cousin',         1.67            'aunt'
29   'estradiol': 'hydroxyprogesterone',         1.33       'estradiol'
30                     'wife': 'nephew',         2.67            'wife'
31                         'mom': 'hey',         0.00             'mom'
32          'stewardess': 'unperformed',         0.00      'stewardess'
33                   'females': 'males',         5.00         'females'
34                'ma': 'massachusetts',         0.00              'ma'
35                  'miss': 'dashwoods',         0.00            'miss'
36                  'nieces': 'nephews',         5.00          'nieces'
37                        'cow': 'goat',         5.00             'cow'
38          'granddaughter': 'grandson',         5.00   'granddaughter'
39                    'hen': 'cackling',         0.00             'hen'
40                'wenches': 'wronging',         0.00         'wenches'
41                   'duchess': 'malfi',         0.00         'duchess'
42               'ballerina': 'yoseloff'         0.00       'ballerina'

                       debiased_1  avg_score_1
0                             NaN          NaN
1             'actress': 'actor',         5.00
2                 'mama': 'papa',         5.00
3                             NaN          NaN
4           'princess': 'prince',         5.00
5    'governesses': 'courtesans',         0.00
6             'abbess': 'cecile',         0.00
7                 'women': 'men',         5.00
8           'widow': 'zarephath',         0.00
9          'ladies': 'gentlemen',         5.00
10                'madam': 'sir',         5.00
11      'baroness': 'councilman',         4.33
12             'niece': 'nephew',         5.00
13           'widows': 'orphans',         2.00
14           'lady': 'gentleman',         5.00
15           'sister': 'brother',         5.00
16                 'nun': 'monk',         5.00
17    'obstetrics': 'gynecology',         1.67
18                  'her': 'his',         5.00
19        'marchioness': 'craik',         0.00
20        'convent': 'monastery',         0.00
21   'priestesses': 'courtesans',         0.00
22               'queen': 'king',         5.00
23                            NaN          NaN
24                            NaN          NaN
25                            NaN          NaN
26                            NaN          NaN
27                            NaN          NaN
28                            NaN          NaN
29                            NaN          NaN
30                            NaN          NaN
31                            NaN          NaN
32                            NaN          NaN
33                            NaN          NaN
34                            NaN          NaN
35                            NaN          NaN
36                            NaN          NaN
37                            NaN          NaN
38                            NaN          NaN
39                            NaN          NaN
40                            NaN          NaN
41                            NaN          NaN
42                            NaN          NaN

In [127]:
original_d2=original_d1.merge(debias_2_merge,how='left',left_on='on',right_on='on')
print(original_d2)

                                original  avg_score_o                on  \
0                  maidservant': 'susa',         1.33     'maidservant'
1                    'actress': 'actor',         5.00         'actress'
2                        'mama': 'yeah',         0.00            'mama'
3                'clitoris': 'frenulum',         0.00        'clitoris'
4             'princess': 'casamassima',         0.00        'princess'
5               'governesses': 'platon',         0.00     'governesses'
6                     'abbess': 'fulda',         0.00          'abbess'
7                        'women': 'men',         5.00           'women'
8                  'widow': 'zarephath',         0.00           'widow'
9                 'ladies': 'gentlemen',         5.00          'ladies'
10                       'madam': 'sir',         5.00           'madam'
11                  'baroness': 'spaak',         0.00        'baroness'
12                    'niece': 'nephew',         5.00           'niece'
13                  'widows': 'orphans',         0.00          'widows'
14                  'lady': 'gentleman',         5.00            'lady'
15                  'sister': 'brother',         5.00          'sister'
16                        'nun': 'monk',         5.00             'nun'
17          'obstetrics': 'gynaecology',         1.67      'obstetrics'
18                          'her': 'he',         5.00             'her'
19                 'marchioness': 'kom',         0.00     'marchioness'
20               'convent': 'monastery',         0.00         'convent'
21         'priestesses': 'darstellung',         0.00     'priestesses'
22                      'queen': 'king',         5.00           'queen'
23                 'empress': 'emperor',         5.00         'empress'
24                     'mommy': 'daddy',         5.00           'mommy'
25        'enchantress': 'relinquishes',         1.67     'enchantress'
26               'estrogen': 'androgen',         5.00        'estrogen'
27                    'goddess': 'gods',         5.00         'goddess'
28                     'aunt': 'cousin',         1.67            'aunt'
29   'estradiol': 'hydroxyprogesterone',         1.33       'estradiol'
30                     'wife': 'nephew',         2.67            'wife'
31                         'mom': 'hey',         0.00             'mom'
32          'stewardess': 'unperformed',         0.00      'stewardess'
33                   'females': 'males',         5.00         'females'
34                'ma': 'massachusetts',         0.00              'ma'
35                  'miss': 'dashwoods',         0.00            'miss'
36                  'nieces': 'nephews',         5.00          'nieces'
37                        'cow': 'goat',         5.00             'cow'
38          'granddaughter': 'grandson',         5.00   'granddaughter'
39                    'hen': 'cackling',         0.00             'hen'
40                'wenches': 'wronging',         0.00         'wenches'
41                   'duchess': 'malfi',         0.00         'duchess'
42               'ballerina': 'yoseloff'         0.00       'ballerina'

                       debiased_1  avg_score_1                     debiased_2  \
0                             NaN          NaN                            NaN
1             'actress': 'actor',         5.00            'actress': 'actor',
2                 'mama': 'papa',         5.00                'mama': 'papa',
3                             NaN          NaN                            NaN
4           'princess': 'prince',         5.00          'princess': 'prince',
5    'governesses': 'courtesans',         0.00   'governesses': 'courtesans',
6             'abbess': 'cecile',         0.00             'abbess': 'fulda',
7                 'women': 'men',         5.00                'women': 'men',
8           'widow': 'zarephath',         0.00          'widow': 'zarephath',
9          'ladies': 'gentlemen',         5.00         'ladies': 'gentlemen',
10                'madam': 'sir',         5.00                            NaN
11      'baroness': 'councilman',         4.33      'baroness': 'courtesans',
12             'niece': 'nephew',         5.00             'niece': 'nephew',
13           'widows': 'orphans',         2.00                            NaN
14           'lady': 'gentleman',         5.00           'lady': 'gentleman',
15           'sister': 'brother',         5.00           'sister': 'brother',
16                 'nun': 'monk',         5.00                 'nun': 'monk',
17    'obstetrics': 'gynecology',         1.67    'obstetrics': 'gynecology',
18                  'her': 'his',         5.00                  'her': 'his',
19        'marchioness': 'craik',         0.00         'marchioness': 'thun',
20        'convent': 'monastery',         0.00        'convent': 'monastery',
21   'priestesses': 'courtesans',         0.00   'priestesses': 'courtesans',
22               'queen': 'king',         5.00               'queen': 'king',
23                            NaN          NaN                            NaN
24                            NaN          NaN                            NaN
25                            NaN          NaN                            NaN
26                            NaN          NaN                            NaN
27                            NaN          NaN                            NaN
28                            NaN          NaN                            NaN
29                            NaN          NaN                            NaN
30                            NaN          NaN                            NaN
31                            NaN          NaN                            NaN
32                            NaN          NaN                            NaN
33                            NaN          NaN                            NaN
34                            NaN          NaN                            NaN
35                            NaN          NaN                            NaN
36                            NaN          NaN                            NaN
37                            NaN          NaN                            NaN
38                            NaN          NaN                            NaN
39                            NaN          NaN                            NaN
40                            NaN          NaN                            NaN
41                            NaN          NaN                            NaN
42                            NaN          NaN                            NaN

    avg_score_2
0           NaN
1          5.00
2          5.00
3           NaN
4          5.00
5          0.00
6          0.00
7          5.00
8          0.00
9          5.00
10          NaN
11         0.00
12         5.00
13          NaN
14         5.00
15         5.00
16         5.00
17         2.67
18         5.00
19         0.00
20         5.00
21         0.00
22         5.00
23          NaN
24          NaN
25          NaN
26          NaN
27          NaN
28          NaN
29          NaN
30          NaN
31          NaN
32          NaN
33          NaN
34          NaN
35          NaN
36          NaN
37          NaN
38          NaN
39          NaN
40          NaN
41          NaN
42          NaN

In [128]:
original_d3=original_d2.merge(debias_3_merge,how='left',left_on='on',right_on='on')
print(original_d3)

                                original  avg_score_o                on  \
0                  maidservant': 'susa',         1.33     'maidservant'
1                    'actress': 'actor',         5.00         'actress'
2                        'mama': 'yeah',         0.00            'mama'
3                'clitoris': 'frenulum',         0.00        'clitoris'
4             'princess': 'casamassima',         0.00        'princess'
5               'governesses': 'platon',         0.00     'governesses'
6                     'abbess': 'fulda',         0.00          'abbess'
7                        'women': 'men',         5.00           'women'
8                  'widow': 'zarephath',         0.00           'widow'
9                 'ladies': 'gentlemen',         5.00          'ladies'
10                       'madam': 'sir',         5.00           'madam'
11                  'baroness': 'spaak',         0.00        'baroness'
12                    'niece': 'nephew',         5.00           'niece'
13                  'widows': 'orphans',         0.00          'widows'
14                  'lady': 'gentleman',         5.00            'lady'
15                  'sister': 'brother',         5.00          'sister'
16                        'nun': 'monk',         5.00             'nun'
17          'obstetrics': 'gynaecology',         1.67      'obstetrics'
18                          'her': 'he',         5.00             'her'
19                 'marchioness': 'kom',         0.00     'marchioness'
20               'convent': 'monastery',         0.00         'convent'
21         'priestesses': 'darstellung',         0.00     'priestesses'
22                      'queen': 'king',         5.00           'queen'
23                 'empress': 'emperor',         5.00         'empress'
24                     'mommy': 'daddy',         5.00           'mommy'
25        'enchantress': 'relinquishes',         1.67     'enchantress'
26               'estrogen': 'androgen',         5.00        'estrogen'
27                    'goddess': 'gods',         5.00         'goddess'
28                     'aunt': 'cousin',         1.67            'aunt'
29   'estradiol': 'hydroxyprogesterone',         1.33       'estradiol'
30                     'wife': 'nephew',         2.67            'wife'
31                         'mom': 'hey',         0.00             'mom'
32          'stewardess': 'unperformed',         0.00      'stewardess'
33                   'females': 'males',         5.00         'females'
34                'ma': 'massachusetts',         0.00              'ma'
35                  'miss': 'dashwoods',         0.00            'miss'
36                  'nieces': 'nephews',         5.00          'nieces'
37                        'cow': 'goat',         5.00             'cow'
38          'granddaughter': 'grandson',         5.00   'granddaughter'
39                    'hen': 'cackling',         0.00             'hen'
40                'wenches': 'wronging',         0.00         'wenches'
41                   'duchess': 'malfi',         0.00         'duchess'
42               'ballerina': 'yoseloff'         0.00       'ballerina'

                       debiased_1  avg_score_1                     debiased_2  \
0                             NaN          NaN                            NaN
1             'actress': 'actor',         5.00            'actress': 'actor',
2                 'mama': 'papa',         5.00                'mama': 'papa',
3                             NaN          NaN                            NaN
4           'princess': 'prince',         5.00          'princess': 'prince',
5    'governesses': 'courtesans',         0.00   'governesses': 'courtesans',
6             'abbess': 'cecile',         0.00             'abbess': 'fulda',
7                 'women': 'men',         5.00                'women': 'men',
8           'widow': 'zarephath',         0.00          'widow': 'zarephath',
9          'ladies': 'gentlemen',         5.00         'ladies': 'gentlemen',
10                'madam': 'sir',         5.00                            NaN
11      'baroness': 'councilman',         4.33      'baroness': 'courtesans',
12             'niece': 'nephew',         5.00             'niece': 'nephew',
13           'widows': 'orphans',         2.00                            NaN
14           'lady': 'gentleman',         5.00           'lady': 'gentleman',
15           'sister': 'brother',         5.00           'sister': 'brother',
16                 'nun': 'monk',         5.00                 'nun': 'monk',
17    'obstetrics': 'gynecology',         1.67    'obstetrics': 'gynecology',
18                  'her': 'his',         5.00                  'her': 'his',
19        'marchioness': 'craik',         0.00         'marchioness': 'thun',
20        'convent': 'monastery',         0.00        'convent': 'monastery',
21   'priestesses': 'courtesans',         0.00   'priestesses': 'courtesans',
22               'queen': 'king',         5.00               'queen': 'king',
23                            NaN          NaN                            NaN
24                            NaN          NaN                            NaN
25                            NaN          NaN                            NaN
26                            NaN          NaN                            NaN
27                            NaN          NaN                            NaN
28                            NaN          NaN                            NaN
29                            NaN          NaN                            NaN
30                            NaN          NaN                            NaN
31                            NaN          NaN                            NaN
32                            NaN          NaN                            NaN
33                            NaN          NaN                            NaN
34                            NaN          NaN                            NaN
35                            NaN          NaN                            NaN
36                            NaN          NaN                            NaN
37                            NaN          NaN                            NaN
38                            NaN          NaN                            NaN
39                            NaN          NaN                            NaN
40                            NaN          NaN                            NaN
41                            NaN          NaN                            NaN
42                            NaN          NaN                            NaN

    avg_score_2                       debiased_3  avg_score_3
0           NaN     'maidservant': 'manservant',         5.00
1          5.00                              NaN          NaN
2          5.00                   'mama': 'mom',         1.00
3           NaN             'clitoris': 'penis',         5.00
4          5.00                              NaN          NaN
5          0.00        'governesses': 'winfred',         0.00
6          0.00              'abbess': 'bingen',         0.00
7          5.00                  'women': 'men',         5.00
8          0.00             'widow': 'daughter',         1.67
9          5.00                'ladies': 'lady',         1.00
10          NaN                              NaN          NaN
11         0.00            'baroness': 'missus',         1.67
12         5.00                 'niece': 'lady',         1.67
13          NaN             'widows': 'orphans',         3.67
14         5.00                 'lady': 'woman',         1.67
15         5.00       'sister': 'granddaughter',         2.00
16         5.00                              NaN          NaN
17         2.67      'obstetrics': 'gynecology',         2.00
18         5.00                     'her': 'he',         5.00
19         0.00        'marchioness': 'egeland',         0.00
20         5.00                              NaN          NaN
21         0.00   'priestesses': 'democratique',         3.67
22         5.00                'queen': 'queens'         2.00
23          NaN                              NaN          NaN
24          NaN                              NaN          NaN
25          NaN                              NaN          NaN
26          NaN                              NaN          NaN
27          NaN                              NaN          NaN
28          NaN                              NaN          NaN
29          NaN                              NaN          NaN
30          NaN                              NaN          NaN
31          NaN                              NaN          NaN
32          NaN                              NaN          NaN
33          NaN                              NaN          NaN
34          NaN                              NaN          NaN
35          NaN                              NaN          NaN
36          NaN                              NaN          NaN
37          NaN                              NaN          NaN
38          NaN                              NaN          NaN
39          NaN                              NaN          NaN
40          NaN                              NaN          NaN
41          NaN                              NaN          NaN
42          NaN                              NaN          NaN

In [129]:
original_d4=original_d3.merge(debias_4_merge,how='left',left_on='on',right_on='on')
print(original_d4)

                                original  avg_score_o                on  \
0                  maidservant': 'susa',         1.33     'maidservant'
1                    'actress': 'actor',         5.00         'actress'
2                        'mama': 'yeah',         0.00            'mama'
3                'clitoris': 'frenulum',         0.00        'clitoris'
4             'princess': 'casamassima',         0.00        'princess'
5               'governesses': 'platon',         0.00     'governesses'
6                     'abbess': 'fulda',         0.00          'abbess'
7                        'women': 'men',         5.00           'women'
8                  'widow': 'zarephath',         0.00           'widow'
9                 'ladies': 'gentlemen',         5.00          'ladies'
10                       'madam': 'sir',         5.00           'madam'
11                  'baroness': 'spaak',         0.00        'baroness'
12                    'niece': 'nephew',         5.00           'niece'
13                  'widows': 'orphans',         0.00          'widows'
14                  'lady': 'gentleman',         5.00            'lady'
15                  'sister': 'brother',         5.00          'sister'
16                        'nun': 'monk',         5.00             'nun'
17          'obstetrics': 'gynaecology',         1.67      'obstetrics'
18                          'her': 'he',         5.00             'her'
19                 'marchioness': 'kom',         0.00     'marchioness'
20               'convent': 'monastery',         0.00         'convent'
21         'priestesses': 'darstellung',         0.00     'priestesses'
22                      'queen': 'king',         5.00           'queen'
23                 'empress': 'emperor',         5.00         'empress'
24                     'mommy': 'daddy',         5.00           'mommy'
25        'enchantress': 'relinquishes',         1.67     'enchantress'
26               'estrogen': 'androgen',         5.00        'estrogen'
27                    'goddess': 'gods',         5.00         'goddess'
28                     'aunt': 'cousin',         1.67            'aunt'
29   'estradiol': 'hydroxyprogesterone',         1.33       'estradiol'
30                     'wife': 'nephew',         2.67            'wife'
31                         'mom': 'hey',         0.00             'mom'
32          'stewardess': 'unperformed',         0.00      'stewardess'
33                   'females': 'males',         5.00         'females'
34                'ma': 'massachusetts',         0.00              'ma'
35                  'miss': 'dashwoods',         0.00            'miss'
36                  'nieces': 'nephews',         5.00          'nieces'
37                        'cow': 'goat',         5.00             'cow'
38          'granddaughter': 'grandson',         5.00   'granddaughter'
39                    'hen': 'cackling',         0.00             'hen'
40                'wenches': 'wronging',         0.00         'wenches'
41                   'duchess': 'malfi',         0.00         'duchess'
42               'ballerina': 'yoseloff'         0.00       'ballerina'

                       debiased_1  avg_score_1                     debiased_2  \
0                             NaN          NaN                            NaN
1             'actress': 'actor',         5.00            'actress': 'actor',
2                 'mama': 'papa',         5.00                'mama': 'papa',
3                             NaN          NaN                            NaN
4           'princess': 'prince',         5.00          'princess': 'prince',
5    'governesses': 'courtesans',         0.00   'governesses': 'courtesans',
6             'abbess': 'cecile',         0.00             'abbess': 'fulda',
7                 'women': 'men',         5.00                'women': 'men',
8           'widow': 'zarephath',         0.00          'widow': 'zarephath',
9          'ladies': 'gentlemen',         5.00         'ladies': 'gentlemen',
10                'madam': 'sir',         5.00                            NaN
11      'baroness': 'councilman',         4.33      'baroness': 'courtesans',
12             'niece': 'nephew',         5.00             'niece': 'nephew',
13           'widows': 'orphans',         2.00                            NaN
14           'lady': 'gentleman',         5.00           'lady': 'gentleman',
15           'sister': 'brother',         5.00           'sister': 'brother',
16                 'nun': 'monk',         5.00                 'nun': 'monk',
17    'obstetrics': 'gynecology',         1.67    'obstetrics': 'gynecology',
18                  'her': 'his',         5.00                  'her': 'his',
19        'marchioness': 'craik',         0.00         'marchioness': 'thun',
20        'convent': 'monastery',         0.00        'convent': 'monastery',
21   'priestesses': 'courtesans',         0.00   'priestesses': 'courtesans',
22               'queen': 'king',         5.00               'queen': 'king',
23                            NaN          NaN                            NaN
24                            NaN          NaN                            NaN
25                            NaN          NaN                            NaN
26                            NaN          NaN                            NaN
27                            NaN          NaN                            NaN
28                            NaN          NaN                            NaN
29                            NaN          NaN                            NaN
30                            NaN          NaN                            NaN
31                            NaN          NaN                            NaN
32                            NaN          NaN                            NaN
33                            NaN          NaN                            NaN
34                            NaN          NaN                            NaN
35                            NaN          NaN                            NaN
36                            NaN          NaN                            NaN
37                            NaN          NaN                            NaN
38                            NaN          NaN                            NaN
39                            NaN          NaN                            NaN
40                            NaN          NaN                            NaN
41                            NaN          NaN                            NaN
42                            NaN          NaN                            NaN

    avg_score_2                       debiased_3  avg_score_3  \
0           NaN     'maidservant': 'manservant',         5.00
1          5.00                              NaN          NaN
2          5.00                   'mama': 'mom',         1.00
3           NaN             'clitoris': 'penis',         5.00
4          5.00                              NaN          NaN
5          0.00        'governesses': 'winfred',         0.00
6          0.00              'abbess': 'bingen',         0.00
7          5.00                  'women': 'men',         5.00
8          0.00             'widow': 'daughter',         1.67
9          5.00                'ladies': 'lady',         1.00
10          NaN                              NaN          NaN
11         0.00            'baroness': 'missus',         1.67
12         5.00                 'niece': 'lady',         1.67
13          NaN             'widows': 'orphans',         3.67
14         5.00                 'lady': 'woman',         1.67
15         5.00       'sister': 'granddaughter',         2.00
16         5.00                              NaN          NaN
17         2.67      'obstetrics': 'gynecology',         2.00
18         5.00                     'her': 'he',         5.00
19         0.00        'marchioness': 'egeland',         0.00
20         5.00                              NaN          NaN
21         0.00   'priestesses': 'democratique',         3.67
22         5.00                'queen': 'queens'         2.00
23          NaN                              NaN          NaN
24          NaN                              NaN          NaN
25          NaN                              NaN          NaN
26          NaN                              NaN          NaN
27          NaN                              NaN          NaN
28          NaN                              NaN          NaN
29          NaN                              NaN          NaN
30          NaN                              NaN          NaN
31          NaN                              NaN          NaN
32          NaN                              NaN          NaN
33          NaN                              NaN          NaN
34          NaN                              NaN          NaN
35          NaN                              NaN          NaN
36          NaN                              NaN          NaN
37          NaN                              NaN          NaN
38          NaN                              NaN          NaN
39          NaN                              NaN          NaN
40          NaN                              NaN          NaN
41          NaN                              NaN          NaN
42          NaN                              NaN          NaN

                       debiased_4  avg_score_4
0    'maidservant': 'manservant',         5.00
1                             NaN          NaN
2                  'mama': 'mom',         1.00
3            'clitoris': 'penis',         5.00
4                             NaN          NaN
5    'governesses': 'courtesans',         0.00
6           'abbess': 'josselin',         0.00
7                 'women': 'men',         5.00
8            'widow': 'daughter',         1.67
9               'ladies': 'lady',         1.67
10                            NaN          NaN
11          'baroness': 'missus',         1.67
12      'niece': 'granddaughter',         1.67
13                            NaN          NaN
14                            NaN          NaN
15     'sister': 'granddaughter',         1.67
16                            NaN          NaN
17    'obstetrics': 'gynecology',         2.00
18                  'her': 'his',         5.00
19        'marchioness': 'mungo',         0.00
20                            NaN          NaN
21   'priestesses': 'courtesans',         0.00
22              'queen': 'queens'         2.00
23                            NaN          NaN
24                            NaN          NaN
25                            NaN          NaN
26                            NaN          NaN
27                            NaN          NaN
28                            NaN          NaN
29                            NaN          NaN
30                            NaN          NaN
31                            NaN          NaN
32                            NaN          NaN
33                            NaN          NaN
34                            NaN          NaN
35                            NaN          NaN
36                            NaN          NaN
37                            NaN          NaN
38                            NaN          NaN
39                            NaN          NaN
40                            NaN          NaN
41                            NaN          NaN
42                            NaN          NaN

In [130]:
original_d5=original_d4.merge(debias_5_merge,how='left',left_on='on',right_on='on')
print(original_d5)

                                original  avg_score_o                on  \
0                  maidservant': 'susa',         1.33     'maidservant'
1                    'actress': 'actor',         5.00         'actress'
2                        'mama': 'yeah',         0.00            'mama'
3                'clitoris': 'frenulum',         0.00        'clitoris'
4             'princess': 'casamassima',         0.00        'princess'
5               'governesses': 'platon',         0.00     'governesses'
6                     'abbess': 'fulda',         0.00          'abbess'
7                        'women': 'men',         5.00           'women'
8                  'widow': 'zarephath',         0.00           'widow'
9                 'ladies': 'gentlemen',         5.00          'ladies'
10                       'madam': 'sir',         5.00           'madam'
11                  'baroness': 'spaak',         0.00        'baroness'
12                    'niece': 'nephew',         5.00           'niece'
13                  'widows': 'orphans',         0.00          'widows'
14                  'lady': 'gentleman',         5.00            'lady'
15                  'sister': 'brother',         5.00          'sister'
16                        'nun': 'monk',         5.00             'nun'
17          'obstetrics': 'gynaecology',         1.67      'obstetrics'
18                          'her': 'he',         5.00             'her'
19                 'marchioness': 'kom',         0.00     'marchioness'
20               'convent': 'monastery',         0.00         'convent'
21         'priestesses': 'darstellung',         0.00     'priestesses'
22                      'queen': 'king',         5.00           'queen'
23                 'empress': 'emperor',         5.00         'empress'
24                     'mommy': 'daddy',         5.00           'mommy'
25        'enchantress': 'relinquishes',         1.67     'enchantress'
26               'estrogen': 'androgen',         5.00        'estrogen'
27                    'goddess': 'gods',         5.00         'goddess'
28                     'aunt': 'cousin',         1.67            'aunt'
29   'estradiol': 'hydroxyprogesterone',         1.33       'estradiol'
30                     'wife': 'nephew',         2.67            'wife'
31                         'mom': 'hey',         0.00             'mom'
32          'stewardess': 'unperformed',         0.00      'stewardess'
33                   'females': 'males',         5.00         'females'
34                'ma': 'massachusetts',         0.00              'ma'
35                  'miss': 'dashwoods',         0.00            'miss'
36                  'nieces': 'nephews',         5.00          'nieces'
37                        'cow': 'goat',         5.00             'cow'
38          'granddaughter': 'grandson',         5.00   'granddaughter'
39                    'hen': 'cackling',         0.00             'hen'
40                'wenches': 'wronging',         0.00         'wenches'
41                   'duchess': 'malfi',         0.00         'duchess'
42               'ballerina': 'yoseloff'         0.00       'ballerina'

                       debiased_1  avg_score_1                     debiased_2  \
0                             NaN          NaN                            NaN
1             'actress': 'actor',         5.00            'actress': 'actor',
2                 'mama': 'papa',         5.00                'mama': 'papa',
3                             NaN          NaN                            NaN
4           'princess': 'prince',         5.00          'princess': 'prince',
5    'governesses': 'courtesans',         0.00   'governesses': 'courtesans',
6             'abbess': 'cecile',         0.00             'abbess': 'fulda',
7                 'women': 'men',         5.00                'women': 'men',
8           'widow': 'zarephath',         0.00          'widow': 'zarephath',
9          'ladies': 'gentlemen',         5.00         'ladies': 'gentlemen',
10                'madam': 'sir',         5.00                            NaN
11      'baroness': 'councilman',         4.33      'baroness': 'courtesans',
12             'niece': 'nephew',         5.00             'niece': 'nephew',
13           'widows': 'orphans',         2.00                            NaN
14           'lady': 'gentleman',         5.00           'lady': 'gentleman',
15           'sister': 'brother',         5.00           'sister': 'brother',
16                 'nun': 'monk',         5.00                 'nun': 'monk',
17    'obstetrics': 'gynecology',         1.67    'obstetrics': 'gynecology',
18                  'her': 'his',         5.00                  'her': 'his',
19        'marchioness': 'craik',         0.00         'marchioness': 'thun',
20        'convent': 'monastery',         0.00        'convent': 'monastery',
21   'priestesses': 'courtesans',         0.00   'priestesses': 'courtesans',
22               'queen': 'king',         5.00               'queen': 'king',
23                            NaN          NaN                            NaN
24                            NaN          NaN                            NaN
25                            NaN          NaN                            NaN
26                            NaN          NaN                            NaN
27                            NaN          NaN                            NaN
28                            NaN          NaN                            NaN
29                            NaN          NaN                            NaN
30                            NaN          NaN                            NaN
31                            NaN          NaN                            NaN
32                            NaN          NaN                            NaN
33                            NaN          NaN                            NaN
34                            NaN          NaN                            NaN
35                            NaN          NaN                            NaN
36                            NaN          NaN                            NaN
37                            NaN          NaN                            NaN
38                            NaN          NaN                            NaN
39                            NaN          NaN                            NaN
40                            NaN          NaN                            NaN
41                            NaN          NaN                            NaN
42                            NaN          NaN                            NaN

    avg_score_2                       debiased_3  avg_score_3  \
0           NaN     'maidservant': 'manservant',         5.00
1          5.00                              NaN          NaN
2          5.00                   'mama': 'mom',         1.00
3           NaN             'clitoris': 'penis',         5.00
4          5.00                              NaN          NaN
5          0.00        'governesses': 'winfred',         0.00
6          0.00              'abbess': 'bingen',         0.00
7          5.00                  'women': 'men',         5.00
8          0.00             'widow': 'daughter',         1.67
9          5.00                'ladies': 'lady',         1.00
10          NaN                              NaN          NaN
11         0.00            'baroness': 'missus',         1.67
12         5.00                 'niece': 'lady',         1.67
13          NaN             'widows': 'orphans',         3.67
14         5.00                 'lady': 'woman',         1.67
15         5.00       'sister': 'granddaughter',         2.00
16         5.00                              NaN          NaN
17         2.67      'obstetrics': 'gynecology',         2.00
18         5.00                     'her': 'he',         5.00
19         0.00        'marchioness': 'egeland',         0.00
20         5.00                              NaN          NaN
21         0.00   'priestesses': 'democratique',         3.67
22         5.00                'queen': 'queens'         2.00
23          NaN                              NaN          NaN
24          NaN                              NaN          NaN
25          NaN                              NaN          NaN
26          NaN                              NaN          NaN
27          NaN                              NaN          NaN
28          NaN                              NaN          NaN
29          NaN                              NaN          NaN
30          NaN                              NaN          NaN
31          NaN                              NaN          NaN
32          NaN                              NaN          NaN
33          NaN                              NaN          NaN
34          NaN                              NaN          NaN
35          NaN                              NaN          NaN
36          NaN                              NaN          NaN
37          NaN                              NaN          NaN
38          NaN                              NaN          NaN
39          NaN                              NaN          NaN
40          NaN                              NaN          NaN
41          NaN                              NaN          NaN
42          NaN                              NaN          NaN

                       debiased_4  avg_score_4  \
0    'maidservant': 'manservant',         5.00
1                             NaN          NaN
2                  'mama': 'mom',         1.00
3            'clitoris': 'penis',         5.00
4                             NaN          NaN
5    'governesses': 'courtesans',         0.00
6           'abbess': 'josselin',         0.00
7                 'women': 'men',         5.00
8            'widow': 'daughter',         1.67
9               'ladies': 'lady',         1.67
10                            NaN          NaN
11          'baroness': 'missus',         1.67
12      'niece': 'granddaughter',         1.67
13                            NaN          NaN
14                            NaN          NaN
15     'sister': 'granddaughter',         1.67
16                            NaN          NaN
17    'obstetrics': 'gynecology',         2.00
18                  'her': 'his',         5.00
19        'marchioness': 'mungo',         0.00
20                            NaN          NaN
21   'priestesses': 'courtesans',         0.00
22              'queen': 'queens'         2.00
23                            NaN          NaN
24                            NaN          NaN
25                            NaN          NaN
26                            NaN          NaN
27                            NaN          NaN
28                            NaN          NaN
29                            NaN          NaN
30                            NaN          NaN
31                            NaN          NaN
32                            NaN          NaN
33                            NaN          NaN
34                            NaN          NaN
35                            NaN          NaN
36                            NaN          NaN
37                            NaN          NaN
38                            NaN          NaN
39                            NaN          NaN
40                            NaN          NaN
41                            NaN          NaN
42                            NaN          NaN

                        debiased_5  avg_score_5
0     'maidservant': 'manservant',         5.00
1                              NaN          NaN
2                   'mama': 'mom',         1.67
3             'clitoris': 'penis',         5.00
4                              NaN          NaN
5     'governesses': 'courtesans',         0.00
6               'abbess': 'fulda',         0.00
7                              NaN          NaN
8                  'widow': 'son',         3.33
9                'ladies': 'lady',         1.67
10                             NaN          NaN
11           'baroness': 'missus',         2.00
12       'niece': 'granddaughter',         2.00
13            'widows': 'orphans',         2.33
14                             NaN          NaN
15      'sister': 'granddaughter',         2.00
16                             NaN          NaN
17                             NaN          NaN
18                    'her': 'he',         5.00
19   'marchioness': 'blessington',         0.00
20                             NaN          NaN
21    'priestesses': 'courtesans',         0.00
22               'queen': 'queens'         2.00
23                             NaN          NaN
24                             NaN          NaN
25                             NaN          NaN
26                             NaN          NaN
27                             NaN          NaN
28                             NaN          NaN
29                             NaN          NaN
30                             NaN          NaN
31                             NaN          NaN
32                             NaN          NaN
33                             NaN          NaN
34                             NaN          NaN
35                             NaN          NaN
36                             NaN          NaN
37                             NaN          NaN
38                             NaN          NaN
39                             NaN          NaN
40                             NaN          NaN
41                             NaN          NaN
42                             NaN          NaN